"""Расширение hand-curated hypothesis-graphs до корпуса из 26 конвейеров nf-core.

Дополняет `build_hand_curated_hypothesis_graphs.py` (спецификация
docs/superpowers/specs/2026-05-20-hand-curated-hypothesis-graphs-design.md):
черновики гипотезных графов для конвейеров, входящих в корпус 26
(гл. 3 диссертации, deep-cache-эксперимент), но отсутствующих в корпусе 20.

Статус: DRAFT — формулировки и пороги подготовлены исполнителем и
подлежат экспертному ревью автора (п. «Кто формулирует» спеки).

Выход: data/hand_curated_hypothesis_graphs_26.json — ровно 26 конвейеров:
17 сохранённых из корпуса 20 + новые из NEW_GRAPHS (см. TARGET_26).
"""
from __future__ import annotations
import json
import sys
from pathlib import Path

try:
    sys.stdout.reconfigure(encoding="utf-8")
except Exception:
    pass

sys.path.insert(0, str(Path(__file__).parent))
from build_hand_curated_hypothesis_graphs import build_graph  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent   # examples/research/planning/
DATA = ROOT / "data"
SRC_JSON = DATA / "hand_curated_hypothesis_graphs.json"
OUT_JSON = DATA / "hand_curated_hypothesis_graphs_26.json"

# Корпус 26: 17 общих с корпусом 20 + 9 новых. Заполняется по итогам
# переписи nfcore_validation.py (28 целей -> фильтр >= 10 узлов).
TARGET_26 = [
    # --- 16 сохранённых из корпуса 20 (eager не парсится -> вне корпуса 26) ---
    "rnaseq", "airrflow", "sarek", "atacseq", "chipseq", "methylseq",
    "hic", "ampliseq", "mag", "viralrecon", "scrnaseq", "taxprofiler",
    "cutandrun", "smrnaseq", "bacass", "nanoseq",
    # --- 10 новых (DRAFT, требуют авторского ревью) ---
    "rnafusion", "raredisease", "funcscan", "oncoanalyser",
    "differentialabundance", "hlatyping", "bactmap", "rnavar",
    "rnasplice", "epitopeprediction",
]
# Список 26 восстановлен переписем nfcore_validation.py (2026-10-05):
# 28 целей - eager (no workflow found) - fetchngs (8 узлов) = 26.
# fetchngs и eager вне корпуса; черновик fetchngs оставлен ниже для полноты.


# === rnafusion === 15 узлов, 5 слоёв (RNA-seq fusion detection) ===
RNAFUSION_HYP = [
    {"id": "qc01", "layer": "QC",
     "text": "среднее качество reads Q30 ≥ 30 на позициях 5'–30'",
     "params": {"q_threshold": 30, "pos_range": "5-30"},
     "source": "Andrews 2010 (FastQC)"},
    {"id": "qc02", "layer": "QC",
     "text": "доля адаптерной контаминации < 5%",
     "params": {"contamination_thr": 0.05, "type": "adapter"},
     "source": "Martin 2011 (Cutadapt); Conesa 2016 §2.2"},
    {"id": "qc03", "layer": "QC",
     "text": "доля рибосомальных reads < 10% (poly(A)-обогащение)",
     "params": {"rrna_thr": 0.10},
     "source": "Conesa 2016 §3.3"},
    {"id": "al01", "layer": "Alignment",
     "text": "≥ 80% reads уникально картируются на референс",
     "params": {"unique_map_rate": 0.80},
     "source": "Dobin 2013 (STAR); Conesa 2016 §3.2"},
    {"id": "al02", "layer": "Alignment",
     "text": "доля сплайс-совместимых выравниваний ≥ 70%",
     "params": {"splice_compat_rate": 0.70},
     "source": "Dobin 2013 (STAR)"},
    {"id": "al03", "layer": "Alignment",
     "text": "доля химерных (chimeric) выравниваний ≤ 1% в норме и выше при наличии фьюжна",
     "params": {"chimeric_rate_ref": 0.01},
     "source": "Haas 2019 (STAR-Fusion)"},
    {"id": "fc01", "layer": "FusionCall",
     "text": "∃ ≥ 1 кандидатная фьюжн-пара с ≥ 3 spanning reads",
     "params": {"spanning_min": 3},
     "source": "Haas 2019 (STAR-Fusion)"},
    {"id": "fc02", "layer": "FusionCall",
     "text": "∃ фьюжн с ≥ 5 spanning и ≥ 2 encompassing reads",
     "params": {"spanning_min": 5, "encompassing_min": 2},
     "source": "Uhrig 2021 (Arriba)"},
    {"id": "fc03", "layer": "FusionCall",
     "text": "фьюжн-кандидаты воспроизводятся двумя коллерами (STAR-Fusion ∩ Arriba непусто)",
     "params": {"callers": ["STAR-Fusion", "Arriba"], "consensus": "intersection"},
     "source": "Uhrig 2021 (Arriba)"},
    {"id": "an01", "layer": "Annotation",
     "text": "фьюжн-пара сохраняет рамку считывания (in-frame)",
     "params": {"frame": "in-frame"},
     "source": "Latysheva & Marsden 2016"},
    {"id": "an02", "layer": "Annotation",
     "text": "фьюжн-пара входит в Census генов рака (COSMIC)",
     "params": {"frame": "in-frame", "database": "COSMIC-Census"},
     "source": "Forbes 2011 (COSMIC); Sondka 2018"},
    {"id": "an03", "layer": "Annotation",
     "text": "фьюжн сохраняет coding-последовательности обоих партнёров",
     "params": {"frame": "in-frame", "coding_retained": "both"},
     "source": "Latysheva & Marsden 2016"},
    {"id": "va01", "layer": "Validation",
     "text": "breakpoint не является read-through (расстояние между партнёрами > 20 kb или разные хромосомы)",
     "params": {"readthrough_kb": 20},
     "source": "Haas 2019 (STAR-Fusion)"},
    {"id": "va02", "layer": "Validation",
     "text": "фьюжн детектируется в биологических репликатах образца",
     "params": {"replicates": "same-sample"},
     "source": "Haas 2019"},
    {"id": "va03", "layer": "Validation",
     "text": "паттерн экспрессии партнёров согласован (оба гена экспрессируются)",
     "params": {"expression_check": True},
     "source": "Uhrig 2021"},
]
RNAFUSION_EDGES = [
    ("qc01", "al01", "картирование требует качественных reads"),
    ("qc02", "al01", "адаптеры снижают mapping rate"),
    ("al01", "fc01", "spanning reads — подмножество картированных"),
    ("al02", "fc01", "сплайс-совместимость отделяет истинные джанкции"),
    ("al03", "fc01", "химерные выравнивания — источник spanning-ридов"),
    ("fc01", "an01", "аннотация рамки оперирует вызванными парами"),
    ("fc02", "an02", "Census-принадлежность оценивается у подтверждённых кандидатов"),
    ("an01", "an02", "in-frame — предпосылка Census-интерпретации"),
    ("fc03", "va01", "консенсусных кандидатов проверяют на read-through"),
    ("va01", "va02", "после отбраковки артефактов — репликация"),
    ("an02", "va03", "экспрессия партнёров осмысленна для онкогенных фьюжнов"),
    ("fc03", "va03", "консенсус устойчив к артефактам одного коллера"),
]

# === raredisease === 15 узлов, 5 слоёв (rare-disease exome/genome) ===
RAREDISEASE_HYP = [
    {"id": "qc01", "layer": "QC",
     "text": "среднее качество reads Q30 ≥ 30",
     "params": {"q_threshold": 30},
     "source": "Andrews 2010 (FastQC)"},
    {"id": "qc02", "layer": "QC",
     "text": "глубина ≥ 20× достигается для ≥ 90% целевых баз",
     "params": {"min_depth": 20, "base_fraction": 0.90},
     "source": "Van der Auwera 2013 (GATK); Lelieveld 2015"},
    {"id": "qc03", "layer": "QC",
     "text": "доля дупликатов < 20%",
     "params": {"dup_rate_max": 0.20},
     "source": "Van der Auwera 2013 (Picard)"},
    {"id": "al01", "layer": "Alignment",
     "text": "≥ 95% reads картированы на референс",
     "params": {"mapped_rate": 0.95},
     "source": "Li 2013 (BWA-MEM)"},
    {"id": "al02", "layer": "Alignment",
     "text": "insert-size в пределах ±3σ от медианы библиотеки",
     "params": {"insert_sigma": 3},
     "source": "Van der Auwera 2013"},
    {"id": "vc01", "layer": "VariantCall",
     "text": "Ti/Tv в кодирующих регионах ∈ [2.0, 3.0]",
     "params": {"region": "CDS", "titv_min": 2.0, "titv_max": 3.0},
     "source": "Guo 2012; Van der Auwera 2013"},
    {"id": "vc02", "layer": "VariantCall",
     "text": "доля целевых баз, пригодных для вызова (callable), ≥ 85%",
     "params": {"region": "CDS", "callable_min": 0.85},
     "source": "Van der Auwera 2013 (CallableLoci)"},
    {"id": "vc03", "layer": "VariantCall",
     "text": "гомозиготность согласована с полом образца (X-инкалл)",
     "params": {"sex_check": True},
     "source": "Richards 2015 (ACMG/AMP); Van der Auwera 2013"},
    {"id": "an01", "layer": "Annotation",
     "text": "варианты классифицированы по ACMG/AMP",
     "params": {"scheme": "ACMG"},
     "source": "Richards 2015 (ACMG/AMP)"},
    {"id": "an02", "layer": "Annotation",
     "text": "∃ вариант класса ACMG 4–5 (likely pathogenic / pathogenic)",
     "params": {"scheme": "ACMG", "class_min": 4},
     "source": "Richards 2015"},
    {"id": "an03", "layer": "Annotation",
     "text": "∃ компаунд-гетерозиготная пара в гене, согласованном с HPO-фенотипом",
     "params": {"scheme": "ACMG", "inheritance": "AR", "phenotype_match": "HPO"},
     "source": "Robinson 2008 (HPO)"},
    {"id": "pr01", "layer": "Prioritisation",
     "text": "ранжирование генов согласуется с HPO-профилем пациента (p < 0.05)",
     "params": {"method": "phenotype-driven", "p_max": 0.05},
     "source": "Köhler 2009 (Phenomizer)"},
    {"id": "pr02", "layer": "Prioritisation",
     "text": "кандидатный ген ранее ассоциирован с фенотипом (OMIM)",
     "params": {"method": "phenotype-driven", "database": "OMIM"},
     "source": "Amberger 2015 (OMIM)"},
    {"id": "pr03", "layer": "Prioritisation",
     "text": "наследование кандидата согласуется с родословной (de novo / AR / AD)",
     "params": {"method": "segregation"},
     "source": "Richards 2015"},
    {"id": "pr04", "layer": "Prioritisation",
     "text": "кандидат объясняет ≥ 80% HPO-терминов пациента",
     "params": {"method": "phenotype-driven", "hpo_coverage": 0.80},
     "source": "Köhler 2009"},
]
RAREDISEASE_EDGES = [
    ("qc01", "al01", "качество reads определяет картирование"),
    ("qc02", "vc01", "глубина нужна для качества вызова"),
    ("qc03", "al01", "дупликаты завышают покрытие и искажают генотипы"),
    ("al01", "vc01", "вызов строится на картированных ридах"),
    ("al02", "vc02", "insert-size влияет на покрытие целевых баз"),
    ("vc01", "an01", "аннотация оперирует вызванными вариантами"),
    ("vc02", "an01", "callability ограничивает множество аннотируемого"),
    ("vc03", "an03", "половая анеуплоидия/гомозиготность влияет на пары"),
    ("an01", "an02", "класс ACMG присваивается аннотированным вариантам"),
    ("an02", "pr01", "кандидаты класса 4–5 подаются на ранжирование"),
    ("an03", "pr03", "наследование пары проверяется сегрегацией"),
    ("pr01", "pr02", "HPO-ранжирование опирается на фено-генные связи OMIM"),
    ("pr02", "pr04", "ассоциированный ген покрывает HPO-термины"),
    ("vc01", "pr01", "качество вызова — предпосылка приоритизации"),
]

# === funcscan === 14 узлов, 5 слоёв (metagenomic AMR/VF screening) ===
FUNCSCAN_HYP = [
    {"id": "qc01", "layer": "QC",
     "text": "среднее качество reads Q30 ≥ 25 (микс платформ)",
     "params": {"q_threshold": 25},
     "source": "Andrews 2010 (FastQC)"},
    {"id": "qc02", "layer": "QC",
     "text": "доля host-контаминации < 10% после вычитания",
     "params": {"host_thr": 0.10},
     "source": "Wood 2019 (Kraken2); KneadData"},
    {"id": "qc03", "layer": "QC",
     "text": "число reads ≥ 5 млн (достаточность покрытия сообщества)",
     "params": {"min_reads": 5000000},
     "source": "Breitwieser 2019 (review)"},
    {"id": "as01", "layer": "Assembly",
     "text": "N50 сборки ≥ 1 kb",
     "params": {"n50_min_bp": 1000},
     "source": "Li 2015 (MEGAHIT)"},
    {"id": "as02", "layer": "Assembly",
     "text": "общий размер сборки согласован с оценкой размера сообщества (metaQUAST)",
     "params": {"check": "metaquast"},
     "source": "Mikheenko 2016 (metaQUAST)"},
    {"id": "as03", "layer": "Assembly",
     "text": "≥ 80% reads возвращаются на сборку (read recruitment)",
     "params": {"recruitment_min": 0.80},
     "source": "Mikheenko 2016"},
    {"id": "am01", "layer": "AMR",
     "text": "∃ ≥ 1 AMR-ген с identity ≥ 90% к референсу CARD",
     "params": {"database": "CARD", "identity_min": 0.90},
     "source": "McArthur 2013 (CARD)"},
    {"id": "am02", "layer": "AMR",
     "text": "∃ AMR-ген с identity ≥ 90% и покрытием длины ≥ 95%",
     "params": {"database": "CARD", "identity_min": 0.90, "coverage_min": 0.95},
     "source": "McArthur 2013"},
    {"id": "am03", "layer": "AMR",
     "text": "AMR-гены покрывают ≥ 3 классов (мультирезистентность)",
     "params": {"database": "CARD", "classes_min": 3},
     "source": "McArthur 2013"},
    {"id": "vi01", "layer": "Virulence",
     "text": "∃ VFDB-гены с identity ≥ 85%",
     "params": {"database": "VFDB", "identity_min": 0.85},
     "source": "Chen 2005 (VFDB)"},
    {"id": "vi02", "layer": "Virulence",
     "text": "токсин-гены согласованы с таксономией носителя",
     "params": {"database": "VFDB", "category": "toxin", "taxon_check": True},
     "source": "Chen 2005"},
    {"id": "co01", "layer": "Context",
     "text": "таксономический профиль согласован между kmer- и marker-подходами",
     "params": {"methods": ["kraken2", "metaphlan"], "agreement": "genus"},
     "source": "Wood 2019; Lu 2017 (Bracken); Beghini 2021 (MetaPhlAn)"},
    {"id": "co02", "layer": "Context",
     "text": "носительство AMR коррелирует с обилием соответствующих таксонов (ρ > 0.6)",
     "params": {"methods": ["kraken2", "metaphlan"], "cor_min": 0.6},
     "source": "McArthur 2013; Beghini 2021"},
    {"id": "co03", "layer": "Context",
     "text": "AMR-профиль различает группы образцов (PERMANOVA p < 0.05)",
     "params": {"test": "permanova", "p_max": 0.05},
     "source": "Anderson 2001"},
]
FUNCSCAN_EDGES = [
    ("qc01", "as01", "качество reads определяет качество сборки"),
    ("qc02", "as01", "host-вычитание предшествует сборке"),
    ("qc03", "as02", "глубина входа отражается на размере сборки"),
    ("as01", "am01", "поиск генов идёт по контигам"),
    ("as02", "am01", "полнота сборки влияет на finding генов"),
    ("as03", "am01", "рекрутмент подтверждает представительность сборки"),
    ("as01", "vi01", "VF-поиск идёт по тем же контигам"),
    ("am01", "co02", "привязка AMR к таксонам требует профилей"),
    ("vi01", "vi02", "таксонная согласованность оценивается у найденных VF"),
    ("co01", "co02", "согласованный профиль — основа корреляции"),
    ("am03", "co03", "мультирезистентность влияет на межгрупповые различия"),
    ("co02", "co03", "таксон-специфичные AMR формируют профиль различий"),
    ("as02", "am02", "покрытие гена оценивается на полной сборке"),
]

# === oncoanalyser === 15 узлов, 5 слоёв (ICGC/ARGO tumor WGS/WTS) — PURPLE-клональная структура ===
ONCOANALYSER_HYP = [
    {"id": "qc01", "layer": "QC",
     "text": "среднее качество reads Q30 ≥ 30",
     "params": {"q_threshold": 30},
     "source": "Andrews 2010 (FastQC)"},
    {"id": "qc02", "layer": "QC",
     "text": "глубина опухолевого и нормального образцов ≥ 30×",
     "params": {"min_depth": 30, "samples": ["tumor", "normal"]},
     "source": "Priestley 2019 (PCAWG); Van der Auwera 2013"},
    {"id": "qc03", "layer": "QC",
     "text": "доля дупликатов < 15%",
     "params": {"dup_rate_max": 0.15},
     "source": "Van der Auwera 2013"},
    {"id": "al01", "layer": "Alignment",
     "text": "≥ 95% reads картированы",
     "params": {"mapped_rate": 0.95},
     "source": "Li 2013 (BWA-MEM)"},
    {"id": "al02", "layer": "Alignment",
     "text": "картирование согласовано между tumor и normal (общий референс, WA < 500)",
     "params": {"wa_max": 500, "samples": ["tumor", "normal"]},
     "source": "Van der Auwera 2013"},
    {"id": "so01", "layer": "Somatic",
     "text": "TMB (SNV/Мб) в диапазоне, ожидаемом для типа опухоли",
     "params": {"metric": "TMB", "tissue_range": True},
     "source": "Chalmers 2017"},
    {"id": "so02", "layer": "Somatic",
     "text": "∃ ≥ 1 driver-мутация в Census-генах",
     "params": {"metric": "driver", "database": "COSMIC-Census"},
     "source": "Sondka 2018 (Census)"},
    {"id": "so03", "layer": "Somatic",
     "text": "SNV-плотность опухолевого образца превышает нормальный ≥ 10×",
     "params": {"metric": "snv_density", "fold_min": 10},
     "source": "Van der Auwera 2013 (MuTect2)"},
    {"id": "pu01", "layer": "Clonal",
     "text": "оценка purity ≥ 0.3 для достоверности соматических вызовов",
     "params": {"purity_min": 0.30},
     "source": "Priestley 2019 (PURPLE)"},
    {"id": "pu02", "layer": "Clonal",
     "text": "оценка ploidy согласована между методами (±10%)",
     "params": {"ploidy_tolerance": 0.10},
     "source": "Priestley 2019"},
    {"id": "si01", "layer": "Signatures",
     "text": "∃ сигнатура SBS, согласующаяся с этиологией образца",
     "params": {"catalog": "COSMIC-SBS", "exposure_min": 0.20},
     "source": "Alexandrov 2013 (signatures)"},
    {"id": "si02", "layer": "Signatures",
     "text": "HRD-оценка (LOH/TAI/LST) указывает на дефицит гомологичной рекомбинации",
     "params": {"catalog": "COSMIC-SBS", "hrd_score": True},
     "source": "Telli 2016 (HRD)"},
    {"id": "su01", "layer": "Clonal",
     "text": "субклональная структура разрешается по CCF (≥ 1 клона с CCF-интервалом, не пересекающим 1)",
     "params": {"ccf_resolved": True},
     "source": "Priestley 2019 (PURPLE)"},
    {"id": "su02", "layer": "Clonal",
     "text": "доля субклональных SNV < 50% (не полностью клональная дивергенция)",
     "params": {"subclonal_max": 0.50},
     "source": "Roth 2014"},
    {"id": "su03", "layer": "Clonal",
     "text": "экспансия клона согласуется с сигнатурами (dominant clone exposure)",
     "params": {"subclonal_max": 0.50, "signature_link": True},
     "source": "Priestley 2019; Alexandrov 2013"},
]
ONCOANALYSER_EDGES = [
    ("qc01", "al01", "качество reads определяет картирование"),
    ("qc02", "so01", "глубина нужна для соматического вызова"),
    ("qc03", "al01", "дупликаты завышают аллельные доли"),
    ("al01", "so01", "сом. вызов строится на картировании"),
    ("al02", "so03", "согласованность пары — предпосылка сравнения плотностей"),
    ("so01", "pu01", "TMB интерпретируется при известной purity"),
    ("pu01", "pu02", "purity/ploidy оцениваются в одной модели"),
    ("so02", "si01", "driver-контекст важен для интерпретации сигнатур"),
    ("si01", "si02", "HRD — частная интерпретация сигнатурного профиля"),
    ("pu01", "su01", "CCF-оценка зависит от purity"),
    ("su01", "su02", "разрешённость клонов определяет долю субклональных"),
    ("si01", "su03", "экспозиции сигнатур привязаны к клонам"),
    ("so03", "su02", "плотность входа ограничивает субклональную декомпозицию"),
    ("qc02", "pu02", "глубина влияет на оценку ploidy"),
]

# === differentialabundance === 14 узлов, 5 слоёв (DA over compositional data) ===
DIFFABUNDANCE_HYP = [
    {"id": "qc01", "layer": "QC",
     "text": "число образцов в группе ≥ 3",
     "params": {"min_group_size": 3},
     "source": "Weiss 2017"},
    {"id": "qc02", "layer": "QC",
     "text": "глубина выровнена после нормализации (rarefaction выходит на плато)",
     "params": {"check": "rarefaction-plateau"},
     "source": "Weiss 2017"},
    {"id": "qc03", "layer": "QC",
     "text": "доля ненулевых признаков ≥ 30% после преваленс-фильтра",
     "params": {"prevalence_min": 0.10, "nonzero_thr": 0.30},
     "source": "Gloor 2016"},
    {"id": "no01", "layer": "Transform",
     "text": "дисперсия стабильна после CLR (гетероскедастичность снята)",
     "params": {"transform": "CLR"},
     "source": "Aitchison 1986; Gloor 2017"},
    {"id": "no02", "layer": "Transform",
     "text": "результат устойчив к выбору псевдосчёта (ΔCLR < 0.1)",
     "params": {"transform": "CLR", "pseudocount_delta": 0.1},
     "source": "Gloor 2017"},
    {"id": "da01", "layer": "Testing",
     "text": "∃ дифференциально обильные таксоны при FDR < 0.05 (ANCOM-BC)",
     "params": {"method": "ANCOM-BC", "fdr_max": 0.05},
     "source": "Lin 2020 (ANCOM-BC)"},
    {"id": "da02", "layer": "Testing",
     "text": "∃ DA-таксоны при FDR < 0.05 (ALDEx2)",
     "params": {"method": "ALDEx2", "fdr_max": 0.05},
     "source": "Fernandes 2013 (ALDEx2)"},
    {"id": "da03", "layer": "Testing",
     "text": "∃ DA-признаки по W-статистике (ANCOM)",
     "params": {"method": "ANCOM", "fdr_max": 0.05},
     "source": "Mandal 2015 (ANCOM)"},
    {"id": "co01", "layer": "Consensus",
     "text": "пересечение DA-множеств (ANCOM-BC ∩ ALDEx2) непусто",
     "params": {"methods": ["ANCOM-BC", "ALDEx2"], "consensus": "intersection"},
     "source": "Weiss 2017"},
    {"id": "co02", "layer": "Consensus",
     "text": "направления log-ratio-изменений согласованы между методами (κ > 0.6)",
     "params": {"methods": ["ANCOM-BC", "ALDEx2", "ANCOM"], "kappa_min": 0.6},
     "source": "Weiss 2017"},
    {"id": "ef01", "layer": "Testing",
     "text": "топ-DA таксон имеет |log2FC| > 1",
     "params": {"method": "ANCOM-BC", "fdr_max": 0.05, "log2fc_min": 1},
     "source": "Lin 2020"},
    {"id": "ef02", "layer": "Testing",
     "text": "обилие топ-DA таксона различается между клиническими категориями",
     "params": {"method": "ANCOM-BC", "fdr_max": 0.05, "stratified": True},
     "source": "Lin 2020"},
    {"id": "di01", "layer": "Diagnostics",
     "text": "β-дисперсия групп объясняется DA-признаками (PERMANOVA p < 0.05)",
     "params": {"test": "permanova", "p_max": 0.05},
     "source": "Anderson 2001; Gloor 2017"},
    {"id": "di02", "layer": "Diagnostics",
     "text": "PCA по CLR разделяет группы в направлении топ-DA таксона",
     "params": {"test": "permanova", "p_max": 0.05, "ordination": "PCA-CLR"},
     "source": "Gloor 2017"},
]
DIFFABUNDANCE_EDGES = [
    ("qc01", "da01", "маломощные группы не дают DA"),
    ("qc02", "da01", "невыровненная глубина маскирует различия"),
    ("qc03", "no01", "фильтрованная матрица преобразуется CLR"),
    ("no01", "da01", "DA-тесты применяются к CLR/смещённой оценке"),
    ("no01", "da02", "альтернативные методы на том же преобразовании"),
    ("no02", "da01", "устойчивость к псевдосчёту — предпосылка выводов"),
    ("da01", "co01", "консенсус строится на индивидуальных вызовах"),
    ("da02", "co01", "второй метод для пересечения"),
    ("da03", "co02", "третий метод для согласованности направлений"),
    ("co01", "ef01", "величина эффекта оценивается у консенсусных таксонов"),
    ("ef01", "ef02", "стратификация уточняет эффект"),
    ("co02", "di01", "согласованные DA объясняют β-дисперсию"),
    ("di01", "di02", "ординация визуализирует тот же сигнал"),
    ("da02", "di01", "второй метод подкрепляет PERMANOVA"),
]

# === hlatyping === 13 узлов, 5 слоёв (HLA typing) ===
HLATYPING_HYP = [
    {"id": "qc01", "layer": "QC",
     "text": "среднее качество reads Q30 ≥ 30",
     "params": {"q_threshold": 30},
     "source": "Andrews 2010 (FastQC)"},
    {"id": "qc02", "layer": "QC",
     "text": "длина reads ≥ 75 bp (требование HLA-тайпинга)",
     "params": {"read_len_min": 75},
     "source": "Szolek 2014 (OptiType)"},
    {"id": "qc03", "layer": "QC",
     "text": "глубина на HLA-локусах ≥ 20×",
     "params": {"locus_depth_min": 20},
     "source": "Zhang 2019 (arcasHLA)"},
    {"id": "al01", "layer": "Alignment",
     "text": "≥ 90% reads картируются на HLA-референс",
     "params": {"mapped_rate": 0.90},
     "source": "Szolek 2014"},
    {"id": "al02", "layer": "Alignment",
     "text": "покрытие экзонов HLA равномерно (fold < 5)",
     "params": {"coverage_fold_max": 5},
     "source": "Zhang 2019"},
    {"id": "ty01", "layer": "Typing",
     "text": "двухполевая типизация разрешена однозначно для ≥ 95% локусов",
     "params": {"resolution": "2-field", "unambiguous_min": 0.95},
     "source": "Szolek 2014"},
    {"id": "ty02", "layer": "Typing",
     "text": "∃ локус с G-group-неоднозначностью",
     "params": {"resolution": "2-field", "unambiguous_min": 0.95, "ambiguity": "G-group"},
     "source": "Robinson 2015 (IPD-IMGT/HLA)"},
    {"id": "ty03", "layer": "Typing",
     "text": "фазовая согласованность достигнута для ≥ 2 локусов",
     "params": {"resolution": "2-field", "phased_min_loci": 2},
     "source": "Zhang 2019"},
    {"id": "op01", "layer": "Optimisation",
     "text": "P-group-разрешение достигается объединением коллеров (arcasHLA ∪ OptiType)",
     "params": {"callers": ["arcasHLA", "OptiType"], "consensus": "union"},
     "source": "Zhang 2019; Szolek 2014"},
    {"id": "op02", "layer": "Optimisation",
     "text": "согласие коллеров ≥ 90% на двухполевом уровне",
     "params": {"callers": ["arcasHLA", "OptiType"], "agreement_min": 0.90},
     "source": "Bai 2018 (review)"},
    {"id": "va01", "layer": "Validation",
     "text": "результаты согласуются с референсной типизацией (HGIG/known-cell-lines)",
     "params": {"reference_set": "HGIG"},
     "source": "Robinson 2015"},
    {"id": "va02", "layer": "Validation",
     "text": "гомозиготность локуса подтверждается аллельным балансом (1:1) и глубиной",
     "params": {"reference_set": "HGIG", "homozygous_check": True},
     "source": "Szolek 2014"},
    {"id": "va03", "layer": "Validation",
     "text": "исходная этническая принадлежность согласуется с частотами аллелей (AF < 0.01 — редкость)",
     "params": {"reference_set": "HGIG", "allele_freq_max": 0.01},
     "source": "Gourraud 2014 (allele frequencies)"},
]
HLATYPING_EDGES = [
    ("qc01", "al01", "качество reads определяет картирование на HLA"),
    ("qc02", "al01", "короткие reads не разрешают полиморфные локусы"),
    ("qc03", "ty01", "глубина нужна для разрешения аллелей"),
    ("al01", "ty01", "типизация строится на картированных ридах"),
    ("al02", "ty03", "равномерность покрытия нужна фазировке"),
    ("ty01", "op01", "объединение коллеров уточняет разрешение"),
    ("ty02", "op01", "G-неоднозначность снимается P-group"),
    ("op01", "op02", "согласие коллеров оценивается на объединении"),
    ("ty01", "va01", "валидация референсом для разрешённых локусов"),
    ("va01", "va02", "гомозиготность проверяется у валидируемых локусов"),
    ("ty03", "va02", "фазировка подтверждает аллельный баланс"),
    ("va01", "va03", "редкость аллелей интерпретируется через частоты"),
]

# === bactmap === 14 узлов, 5 слоёв (bacterial population genomics) ===
BACTMAP_HYP = [
    {"id": "qc01", "layer": "QC",
     "text": "среднее качество reads Q30 ≥ 30",
     "params": {"q_threshold": 30},
     "source": "Andrews 2010 (FastQC)"},
    {"id": "qc02", "layer": "QC",
     "text": "покрытие референса ≥ 30× для ≥ 90% баз",
     "params": {"min_depth": 30, "base_fraction": 0.90},
     "source": "Seemann 2015 (snippy)"},
    {"id": "re01", "layer": "Reference",
     "text": "≥ 95% reads картируются на референсный геном (видовое соответствие)",
     "params": {"mapped_rate": 0.95},
     "source": "Li 2013 (BWA-MEM); Wood 2019 (Kraken2)"},
    {"id": "re02", "layer": "Reference",
     "text": "MLST-профиль образца согласован со схемой референса",
     "params": {"scheme": "pubmlst"},
     "source": "Larsen 2012 (MLST)"},
    {"id": "vc01", "layer": "VariantCall",
     "text": "SNV-дивергенция от референса < 5% (внутривидовой диапазон)",
     "params": {"divergence_max": 0.05},
     "source": "Seemann 2015"},
    {"id": "vc02", "layer": "VariantCall",
     "text": "доля гетерозиготных локусов < 1% (гаплоидный геном, без контаминации)",
     "params": {"heterozygous_max": 0.01},
     "source": "Seemann 2015"},
    {"id": "vc03", "layer": "VariantCall",
     "text": "INDEL/SNV ratio < 0.1 (качество выравнивания)",
     "params": {"indel_snv_max": 0.10},
     "source": "Van der Auwera 2013"},
    {"id": "rc01", "layer": "Recombination",
     "text": "доля генома в рекомбинационных блоках < 50% (после Gubbins)",
     "params": {"recomb_frac_max": 0.50},
     "source": "Croucher 2015 (Gubbins)"},
    {"id": "rc02", "layer": "Recombination",
     "text": "рекомбинация не маскирует вертикальный сигнал (консенсусное дерево устойчиво)",
     "params": {"recomb_frac_max": 0.50, "tree_stable": True},
     "source": "Croucher 2015"},
    {"id": "ph01", "layer": "Phylogeny",
     "text": "филогения (IQ-TREE, GTR+ASC) с bootstrap ≥ 90 на ключевых ветвях",
     "params": {"tool": "IQ-TREE", "bootstrap_min": 90},
     "source": "Nguyen 2015 (IQ-TREE)"},
    {"id": "ph02", "layer": "Phylogeny",
     "text": "кластеры по SNP-расстоянию (< 20 SNV) выделяют эпидемиологические группы",
     "params": {"tool": "IQ-TREE", "bootstrap_min": 90, "snp_cluster_max": 20},
     "source": "Harris 2010 (MRSA whole-genome)"},
    {"id": "ph03", "layer": "Phylogeny",
     "text": "топология устойчива к удалению рекомбинации (RF-расстояние < 0.1)",
     "params": {"rf_max": 0.10},
     "source": "Croucher 2015; Nguyen 2015"},
    {"id": "su01", "layer": "Phylogeny",
     "text": "снип-кластеры согласуются с метаданными (время/место выделения)",
     "params": {"metadata": ["date", "location"], "snp_cluster_max": 20},
     "source": "Harris 2010"},
    {"id": "su02", "layer": "Phylogeny",
     "text": "скорость накопления SNV согласуется с видом (часы молекулярных часов)",
     "params": {"metadata": ["date", "location"], "clock_check": True},
     "source": "Didelot 2012 (molecular clock)"},
]
BACTMAP_EDGES = [
    ("qc01", "re01", "качество reads определяет картирование на референс"),
    ("qc02", "vc01", "покрытие нужно для вызова SNV"),
    ("re01", "vc01", "вызов строится на картированных ридах"),
    ("re02", "vc01", "соответствие схеме — предпосылка внутривидового вызова"),
    ("vc01", "vc02", "дивергенция ограничивает долю гетерозиготных"),
    ("vc03", "rc01", "INDEL-нагрузка искажает рекомбинационные блоки"),
    ("vc01", "rc01", "SNV-карта — вход Gubbins"),
    ("rc01", "rc02", "после разметки блоков проверяется устойчивость"),
    ("rc02", "ph01", "вертикальный сигнал определяет филогению"),
    ("ph01", "ph02", "кластеры определяются на построенном дереве"),
    ("rc01", "ph03", "устойчивость оценивается сравнением с/без фильтра"),
    ("ph02", "su01", "эпидкластеры сопоставляются с метаданными"),
    ("vc01", "su02", "SNV-числа нужны для оценки часов"),
    ("su01", "su02", "временные метки кластеров дают скорость"),
]

# === rnavar === 14 узлов, 5 слоёв (RNA variant calling / editing) ===
RNAVAR_HYP = [
    {"id": "qc01", "layer": "QC",
     "text": "среднее качество reads Q30 ≥ 30",
     "params": {"q_threshold": 30},
     "source": "Andrews 2010 (FastQC)"},
    {"id": "qc02", "layer": "QC",
     "text": "доля рибосомальных reads < 10%",
     "params": {"rrna_thr": 0.10},
     "source": "Conesa 2016 §3.3"},
    {"id": "al01", "layer": "Alignment",
     "text": "≥ 80% reads уникально картированы (STAR 2-pass)",
     "params": {"unique_map_rate": 0.80, "mode": "2-pass"},
     "source": "Dobin 2013 (STAR)"},
    {"id": "al02", "layer": "Alignment",
     "text": "≥ 85% выровненных reads имеют MAPQ ≥ 20",
     "params": {"mapq_min": 20, "mapq_frac": 0.85},
     "source": "Dobin 2013"},
    {"id": "vc01", "layer": "VariantCall",
     "text": "∃ ≥ 1 вариант с VAF ≥ 0.2 и глубиной ≥ 20",
     "params": {"vaf_min": 0.20, "depth_min": 20},
     "source": "Van der Auwera 2013 (GATK)"},
    {"id": "vc02", "layer": "VariantCall",
     "text": "Ti/Tv ∈ [1.5, 3.0] (РНК-диапазон)",
     "params": {"titv_min": 1.5, "titv_max": 3.0},
     "source": "Van der Auwera 2013"},
    {"id": "vc03", "layer": "VariantCall",
     "text": "A→G-замены доминируют среди транзиций (сигнатура A-to-I редактирования)",
     "params": {"editing_signature": "A2G"},
     "source": "Bass 2002 (A-to-I editing)"},
    {"id": "ed01", "layer": "Editing",
     "text": "∃ сайты, аннотированные в RADAR",
     "params": {"database": "RADAR"},
     "source": "Ramaswami 2013 (RADAR)"},
    {"id": "ed02", "layer": "Editing",
     "text": "∃ RADAR-сайт, не входящий в dbSNP",
     "params": {"database": "RADAR", "exclude": "dbSNP"},
     "source": "Ramaswami 2013"},
    {"id": "ed03", "layer": "Editing",
     "text": "сайты вне повторов (Alu) сохраняются после фильтра",
     "params": {"database": "RADAR", "exclude": "dbSNP", "repeat_filter": "Alu"},
     "source": "Bass 2002"},
    {"id": "fi01", "layer": "Filtering",
     "text": "после фильтров (VAF, strand-bias, mappability) остаётся ≥ 1 кандидата",
     "params": {"filters": ["VAF", "strand-bias", "mappability"]},
     "source": "Van der Auwera 2013 (VQSR)"},
    {"id": "fi02", "layer": "Filtering",
     "text": "аллельно-специфичная экспрессия согласована (Fisher p < 0.05)",
     "params": {"filters": ["VAF", "strand-bias", "mappability"], "ase_p_max": 0.05},
     "source": "Van der Auwera 2013; Wang 2011 (ASE)"},
    {"id": "sp01", "layer": "VariantCall",
     "text": "варианты сплайс-сайтов (±2 bp) согласованы с SJ-поддержкой STAR",
     "params": {"region": "splice-sites", "window_bp": 2},
     "source": "Dobin 2013"},
    {"id": "sp02", "layer": "VariantCall",
     "text": "доля variants в сплайс-области соответствует экспрессии генов",
     "params": {"region": "splice-sites", "window_bp": 2, "expression_link": True},
     "source": "Wang 2008 (splicing); Dobin 2013"},
]
RNAVAR_EDGES = [
    ("qc01", "al01", "качество reads определяет картирование"),
    ("qc02", "al01", "рРНК-примеси снижают информативное покрытие"),
    ("al01", "vc01", "вызов строится на картированных ридах"),
    ("al02", "fi01", "MAPQ-фильтрация отсекает мульти-картирование"),
    ("vc01", "vc02", "Ti/Tv оценивается по вызванным вариантам"),
    ("vc03", "ed01", "A→G-кандидаты сверяются с RADAR"),
    ("ed01", "ed02", "аннотированные сайты чистятся от SNPs"),
    ("ed02", "ed03", "повторы — следующий фильтр"),
    ("vc01", "fi01", "фильтрация применяется к вызовам"),
    ("fi01", "fi02", "ASE оценивается по прошедшим фильтр"),
    ("al01", "sp01", "SJ-контекст берётся из выравнивания STAR"),
    ("sp01", "sp02", "экспрессионная привязка сплайс-вариантов"),
    ("ed03", "fi02", "редактирование и ASE на общем множестве"),
    ("vc02", "sp01", "контекст замен в сплайс-областях"),
]

# === rnasplice === 14 узлов, 5 слоёв (differential splicing) ===
RNASPLICE_HYP = [
    {"id": "qc01", "layer": "QC",
     "text": "среднее качество reads Q30 ≥ 30",
     "params": {"q_threshold": 30},
     "source": "Andrews 2010 (FastQC)"},
    {"id": "qc02", "layer": "QC",
     "text": "доля рибосомальных reads < 10%",
     "params": {"rrna_thr": 0.10},
     "source": "Conesa 2016 §3.3"},
    {"id": "al01", "layer": "Alignment",
     "text": "≥ 80% reads уникально картированы сплайс-выравнивателем",
     "params": {"unique_map_rate": 0.80, "aligner": "STAR"},
     "source": "Dobin 2013"},
    {"id": "sj01", "layer": "SpliceJunctions",
     "text": "≥ 10 аннотированных джанкций поддержаны ≥ 10 reads",
     "params": {"annotation": "GTF", "support_min": 10, "junctions_min": 10},
     "source": "Dobin 2013 (SJ module)"},
    {"id": "sj02", "layer": "SpliceJunctions",
     "text": "доля неаннотированных джанкций < 20%",
     "params": {"annotation": "GTF", "novel_frac_max": 0.20},
     "source": "Dobin 2013"},
    {"id": "sj03", "layer": "SpliceJunctions",
     "text": "доля включения ψ (PSI) вычислима для ≥ 1000 событий",
     "params": {"annotation": "GTF", "psi_min_count": 1000},
     "source": "Shen 2014 (rMATS)"},
    {"id": "ev01", "layer": "Events",
     "text": "∃ ≥ 1 cassette-событие (SE) с поддержкой ≥ 10 junction-reads",
     "params": {"event": "SE", "support_min": 10},
     "source": "Shen 2014 (rMATS)"},
    {"id": "ev02", "layer": "Events",
     "text": "события всех пяти типов (SE, A3SS, A5SS, RI, MXE) присутствуют в выходе rMATS",
     "params": {"event": "SE", "types_all": ["SE", "A3SS", "A5SS", "RI", "MXE"]},
     "source": "Shen 2014 (rMATS)"},
    {"id": "ev03", "layer": "Events",
     "text": "∃ ≥ 1 транскрипт с дифференциальным использованием (DTU, DRIMSeq)",
     "params": {"event": "SE", "analysis": "DTU"},
     "source": "Nowicka 2016 (DRIMSeq)"},
    {"id": "di01", "layer": "Differential",
     "text": "∃ дифференциально сплайсируемые события при FDR < 0.05",
     "params": {"test": "rMATS", "fdr_max": 0.05},
     "source": "Shen 2014 (rMATS)"},
    {"id": "di02", "layer": "Differential",
     "text": "топ-событие имеет |Δψ| ≥ 0.1",
     "params": {"test": "rMATS", "fdr_max": 0.05, "delta_psi_min": 0.1},
     "source": "Shen 2014 (rMATS)"},
    {"id": "di03", "layer": "Differential",
     "text": "топ-событие затрагивает ген, связанный с условием (GO/OMIM)",
     "params": {"test": "rMATS", "fdr_max": 0.05, "gene_link": "GO"},
     "source": "Ashburner 2000 (GO)"},
    {"id": "va01", "layer": "Differential",
     "text": "Δψ коррелирует с exon-inclusion-метрикой (RT-PCR-валидируемая)",
     "params": {"cor_with": "PSI"},
     "source": "Shen 2014 (rMATS)"},
    {"id": "va02", "layer": "Differential",
     "text": "реплики согласованы по топ-событиям (Spearman ρ > 0.8)",
     "params": {"cor_with": "PSI", "replicate_rho_min": 0.8},
     "source": "Shen 2014 (rMATS)"},
]
RNASPLICE_EDGES = [
    ("qc01", "al01", "качество reads определяет сплайс-выравнивание"),
    ("qc02", "al01", "рРНК-примеси не дают джанкций"),
    ("al01", "sj01", "джанкции извлекаются из выравнивания"),
    ("sj01", "sj02", "доля новых оценивается по поддержанным"),
    ("sj01", "ev01", "cassette-события собираются из джанкций"),
    ("sj03", "ev02", "типизация событий опирается на ψ-профиль"),
    ("ev01", "ev03", "учёт типов событий покрывает модуль"),
    ("ev02", "di01", "rMATS-тест применяется к типизированным событиям"),
    ("ev03", "di01", "достаточность событий — мощность теста"),
    ("di01", "di02", "величина эффекта у значимых событий"),
    ("di01", "di03", "биологическая интерпретация топ-событий"),
    ("di02", "va01", "Δψ сверяется с exon-inclusion"),
    ("di01", "va02", "воспроизводимость репликатов"),
    ("sj02", "ev01", "неаннотированные джанкции влияют состав событий"),
]

# === fetchngs === 13 узлов, 5 слоёв (SRA/ENA retrieval + QC) — FALLBACK ===
FETCHNGS_HYP = [
    {"id": "qc01", "layer": "QC",
     "text": "среднее качество reads Q30 ≥ 30",
     "params": {"q_threshold": 30},
     "source": "Andrews 2010 (FastQC)"},
    {"id": "qc02", "layer": "QC",
     "text": "доля N-базов < 5%",
     "params": {"n_content_max": 0.05},
     "source": "Andrews 2010"},
    {"id": "co01", "layer": "Content",
     "text": "длина reads ≥ 50 bp (пригодность к картированию)",
     "params": {"read_len_min": 50},
     "source": "Conesa 2016 §2"},
    {"id": "co02", "layer": "Content",
     "text": "GC-распределение одномодально (библиотека без смешения)",
     "params": {"gc_check": "unimodal"},
     "source": "Andrews 2010"},
    {"id": "ct01", "layer": "Contamination",
     "text": "целевой организм доминирует в таксономическом профиле (≥ 90%)",
     "params": {"tool": "kraken2", "target_frac_min": 0.90},
     "source": "Wood 2019 (Kraken2)"},
    {"id": "ct02", "layer": "Contamination",
     "text": "отсутствие баркод-гипердоминирования (index hopping < 5%)",
     "params": {"tool": "kraken2", "target_frac_min": 0.90, "hopping_max": 0.05},
     "source": "Sinigalia 2021 (index hopping)"},
    {"id": "me01", "layer": "Metadata",
     "text": "метаданные SRA (layout, platform) согласованы с фактическим содержимым FASTQ",
     "params": {"check": "sra-vs-fastq"},
     "source": "Leinonen 2011 (SRA)"},
    {"id": "me02", "layer": "Metadata",
     "text": "раны одного образца консистентны (длины, платформа, layout)",
     "params": {"check": "sra-vs-fastq", "scope": "per-sample"},
     "source": "Leinonen 2011"},
    {"id": "re01", "layer": "Series",
     "text": "образцы одной серии имеют согласованную library-strategy",
     "params": {"scope": "per-series"},
     "source": "Leinonen 2011"},
    {"id": "re02", "layer": "Series",
     "text": "биологические репликаты серии близки по глубине (CV < 0.5)",
     "params": {"scope": "per-series", "depth_cv_max": 0.5},
     "source": "Conesa 2016 §2"},
    {"id": "de01", "layer": "Depth",
     "text": "глубина образца ≥ 1 млн reads (минимум для QC-заключения)",
     "params": {"min_reads": 1000000},
     "source": "Conesa 2016"},
    {"id": "de02", "layer": "Depth",
     "text": "глубина достаточна для заявленного анализа (по типу данных)",
     "params": {"min_reads": 1000000, "analysis_specific": True},
     "source": "Conesa 2016"},
    {"id": "out01", "layer": "Output",
     "text": "FASTQ распарены и полны (R1/R2 согласованы по числу reads)",
     "params": {"paired_check": True},
     "source": "Andrews 2010"},
]
FETCHNGS_EDGES = [
    ("qc01", "co01", "длина оценивается вместе с качеством"),
    ("qc02", "co02", "N-базы искажают GC-профиль"),
    ("co01", "ct01", "картируемость — предпосылка таксономии"),
    ("ct01", "ct02", "hopping оценивается при доминировании цели"),
    ("co02", "me01", "GC-аномалии сверяются с метаданными"),
    ("me01", "me02", "пер-ранная согласованность → пер-образцовая"),
    ("me02", "re01", "образцы сводятся в серии"),
    ("re01", "re02", "стратегия серии задаёт ожидание глубины"),
    ("re02", "de01", "реплики задают масштаб глубины"),
    ("de01", "de02", "минимум → достаточность под анализ"),
    ("qc01", "out01", "парность оценивается после QC"),
    ("co01", "de01", "длина влияет на эффективную глубину"),
    ("out01", "de02", "полные пары — предпосылка оценки достаточности"),
]

# === epitopeprediction === 13 узлов, 5 слоёв (MHC binding prediction) — FALLBACK ===
EPITOPEPREDICTION_HYP = [
    {"id": "in01", "layer": "Input",
     "text": "вариантные пептиды 8–11 aa сгенерированы из аннотированных SNV (MHC-I)",
     "params": {"peptide_len": [8, 11], "mhc_class": "I"},
     "source": "Reynisson 2020 (netMHCpan 4.1)"},
    {"id": "in02", "layer": "Input",
     "text": "пептидная библиотека покрывает ≥ 3 HLA-аллеля пациента",
     "params": {"peptide_len": [8, 11], "mhc_class": "I", "alleles_min": 3},
     "source": "Reynisson 2020; O'Donnell 2020 (MHCflurry 2.0)"},
    {"id": "in03", "layer": "Input",
     "text": "пептиды 15-меры сгенерированы для MHC-II",
     "params": {"peptide_len": [15], "mhc_class": "II"},
     "source": "Reynisson 2020b (NetMHCIIpan 4.0)"},
    {"id": "mh01", "layer": "MHCI",
     "text": "∃ ≥ 1 пептид с %Rank ≤ 2 (binder, netMHCpan)",
     "params": {"mhc_class": "I", "rank_max": 2.0},
     "source": "Reynisson 2020"},
    {"id": "mh02", "layer": "MHCI",
     "text": "∃ ≥ 1 пептид с %Rank ≤ 0.5 (strong binder)",
     "params": {"mhc_class": "I", "rank_max": 0.5},
     "source": "Reynisson 2020"},
    {"id": "mh03", "layer": "MHCI",
     "text": "∃ binder, подтверждённый elution-предиктором (BA+EL)",
     "params": {"mhc_class": "I", "rank_max": 2.0, "elution": True},
     "source": "Reynisson 2020"},
    {"id": "mh2_01", "layer": "MHCII",
     "text": "∃ ≥ 1 MHC-II binder с %Rank ≤ 5",
     "params": {"mhc_class": "II", "rank_max": 5.0},
     "source": "Reynisson 2020b"},
    {"id": "mh2_02", "layer": "MHCII",
     "text": "∃ MHC-II binder, согласованный между методами (NetMHCIIpan ∩ MHCnuggets)",
     "params": {"mhc_class": "II", "rank_max": 5.0, "consensus": "intersection"},
     "source": "O'Donnell 2020"},
    {"id": "ra01", "layer": "Ranking",
     "text": "топ-1% пептидов покрывают ≥ 3 аллеля пациента (ширина ответа)",
     "params": {"top_pct": 1, "alleles_min": 3},
     "source": "Reynisson 2020"},
    {"id": "ra02", "layer": "Ranking",
     "text": "∃ neoepitope из driver-мутации в топ-10",
     "params": {"top_pct": 1, "alleles_min": 3, "source_variants": "drivers"},
     "source": "Sondka 2018 (Census)"},
    {"id": "cv01", "layer": "CrossValidation",
     "text": "BA- и EL-ранжирования согласованы (ρ > 0.7)",
     "params": {"cor_min": 0.7},
     "source": "Reynisson 2020"},
    {"id": "cv02", "layer": "CrossValidation",
     "text": "высокораффинные пептиды происходят из экспрессируемых генов (RNA-seq)",
     "params": {"cor_min": 0.7, "expression_link": True},
     "source": "O'Donnell 2020"},
    {"id": "cv03", "layer": "CrossValidation",
     "text": "предсказанные binder'ы не концентрируются в self-пептидах (контроль аутоиммунности)",
     "params": {"cor_min": 0.7, "self_check": True},
     "source": "Reynisson 2020"},
]
EPITOPEPREDICTION_EDGES = [
    ("in01", "mh01", "MHC-I прогноз по 8–11-мерам"),
    ("in02", "mh01", "мультиаллельность расширяет поиск"),
    ("in03", "mh2_01", "MHC-II прогноз по 15-мерам"),
    ("mh01", "mh02", "strong binder — подмножество binder'ов"),
    ("mh01", "mh03", "elution-подтверждение у binder'ов"),
    ("mh2_01", "mh2_02", "консенсус методов по MHC-II"),
    ("mh02", "ra01", "ранжирование оперирует сильными кандидатами"),
    ("ra01", "ra02", "driver-происхождение в топе"),
    ("mh03", "cv01", "согласование BA/EL по подтверждённым"),
    ("ra02", "cv02", "экспрессия источника neoepitope"),
    ("cv01", "cv03", "self-контроль на согласованном ранжировании"),
    ("mh2_02", "cv01", "межметодное согласие — часть кросс-проверки"),
    ("in01", "ra02", "вариантные пептиды несут driver-происхождение"),
]

NEW_GRAPHS = {
    "rnafusion": (RNAFUSION_HYP, RNAFUSION_EDGES),
    "raredisease": (RAREDISEASE_HYP, RAREDISEASE_EDGES),
    "funcscan": (FUNCSCAN_HYP, FUNCSCAN_EDGES),
    "oncoanalyser": (ONCOANALYSER_HYP, ONCOANALYSER_EDGES),
    "differentialabundance": (DIFFABUNDANCE_HYP, DIFFABUNDANCE_EDGES),
    "hlatyping": (HLATYPING_HYP, HLATYPING_EDGES),
    "bactmap": (BACTMAP_HYP, BACTMAP_EDGES),
    "rnavar": (RNAVAR_HYP, RNAVAR_EDGES),
    "rnasplice": (RNASPLICE_HYP, RNASPLICE_EDGES),
    # fallback-кандидаты (не входят в TARGET_26, пока не потребуется):
    "fetchngs": (FETCHNGS_HYP, FETCHNGS_EDGES),
    "epitopeprediction": (EPITOPEPREDICTION_HYP, EPITOPEPREDICTION_EDGES),
}


def main():
    src = json.loads(SRC_JSON.read_text(encoding="utf-8"))
    out = {}
    missing = []
    for key in TARGET_26:
        if key in src:
            out[key] = src[key]
        elif key in NEW_GRAPHS:
            hyp, edges = NEW_GRAPHS[key]
            out[key] = build_graph(f"nf-core/{key}", hyp, edges)
        else:
            missing.append(key)
    if missing:
        raise SystemExit(f"TARGET_26 содержит неизвестные конвейеры: {missing}")

    OUT_JSON.write_text(json.dumps(out, indent=2, ensure_ascii=False),
                        encoding="utf-8")
    print(f"Saved {OUT_JSON}: {len(out)} конвейеров")
    for k, g in out.items():
        tag = "новый(DRAFT)" if k in NEW_GRAPHS and k not in src else "сохранён"
        print(f"  {k:24s} |H|={g['n_hypotheses']:3d}  "
              f"sub={g['n_subsumption_edges']:2d} inter={g['n_inter_layer_edges']:2d}  {tag}")


if __name__ == "__main__":
    main()
