"""Построение hand-curated hypothesis-graphs для nf-core/rnaseq
и~nf-core/airrflow по spec
docs/superpowers/specs/2026-05-20-hand-curated-hypothesis-graphs-design.md.

Структура:
- Список гипотез с метаданными (id, layer, text, params, source).
- Список межслоевых рёбер (экспертно).
- Subsumption-edges внутри слоя выводятся автоматически по
  включению множеств параметров (упрощённая Hyppo-логика).
"""
from __future__ import annotations
import json
import sys
from pathlib import Path

try:
    sys.stdout.reconfigure(encoding="utf-8")
except Exception:
    pass

ROOT = Path(__file__).resolve().parent.parent   # examples/research/iip2026/
CACHE = ROOT / "cache"
OUT_DIR = ROOT / "out"
DATA  = ROOT / "data"
CACHE.mkdir(parents=True, exist_ok=True)
OUT_DIR.mkdir(parents=True, exist_ok=True)
DATA.mkdir(parents=True, exist_ok=True)

OUT = DATA / "hand_curated_hypothesis_graphs.json"


# === rnaseq === 18 узлов, 5 слоёв ===
RNASEQ_HYP = [
    # Layer 0: QC
    {"id": "qc01", "layer": "QC",
     "text": "среднее качество reads Q30 ≥ 30 на позициях 5'–30'",
     "params": {"q_threshold": 30, "pos_range": "5-30"},
     "source": "Andrews 2010 (FastQC); Conesa 2016 §2.1"},
    {"id": "qc02", "layer": "QC",
     "text": "GC-распределение reads соответствует ожидаемому для вида",
     "params": {"check": "gc_distribution"},
     "source": "Conesa 2016 §2.1"},
    {"id": "qc03", "layer": "QC",
     "text": "доля адаптерной контаминации < 5%",
     "params": {"contamination_thr": 0.05, "type": "adapter"},
     "source": "Martin 2011 (Cutadapt); Conesa 2016 §2.2"},
    # Layer 1: Alignment
    {"id": "al01", "layer": "Alignment",
     "text": "≥ 80% reads уникально картируются на референс",
     "params": {"unique_map_rate": 0.80},
     "source": "Dobin 2013 (STAR); Conesa 2016 §3.2"},
    {"id": "al02", "layer": "Alignment",
     "text": "splice-junctions из аннотации поддерживаются ≥ 10 reads",
     "params": {"sj_support": 10, "sj_source": "annotation"},
     "source": "Dobin 2013 §4"},
    {"id": "al03", "layer": "Alignment",
     "text": "доля reads в rRNA-регионах < 10% (poly(A)-обогащение)",
     "params": {"rrna_rate": 0.10, "library": "polyA"},
     "source": "Conesa 2016 §3.3"},
    # Layer 2: Counting
    {"id": "ct01", "layer": "Counting",
     "text": "среднее число reads на ген ≥ 1 для ≥ 50% аннотированных генов",
     "params": {"min_reads_per_gene": 1, "gene_coverage": 0.50},
     "source": "Liao 2014 (featureCounts); Conesa 2016 §4"},
    {"id": "ct02", "layer": "Counting",
     "text": "доля reads на feature (exonic) ≥ 60%",
     "params": {"feature_rate": 0.60, "feature_type": "exon"},
     "source": "Liao 2014"},
    # Layer 3: DE/Statistics
    {"id": "de01", "layer": "DE",
     "text": "∃ DE-гены между условиями A и B при FDR < 0.05",
     "params": {"fdr": 0.05, "test": "wald"},
     "source": "Love 2014 (DESeq2)"},
    {"id": "de02", "layer": "DE",
     "text": "∃ up-регулируемые DE-гены (log₂FC > 1, FDR < 0.05)",
     "params": {"fdr": 0.05, "test": "wald", "direction": "up",
                "lfc_thr": 1.0},
     "source": "Love 2014; subsumption(de01)"},
    {"id": "de03", "layer": "DE",
     "text": "∃ down-регулируемые DE-гены (log₂FC < -1, FDR < 0.05)",
     "params": {"fdr": 0.05, "test": "wald", "direction": "down",
                "lfc_thr": 1.0},
     "source": "Love 2014; subsumption(de01)"},
    {"id": "de04", "layer": "DE",
     "text": "дисперсия gene-counts стабилизируется после VST/rlog",
     "params": {"transform": "vst"},
     "source": "Love 2014 §3"},
    {"id": "de05", "layer": "DE",
     "text": "PCA по top-вариабельным генам разделяет условия A и B",
     "params": {"method": "pca", "top_var_genes": 500},
     "source": "Love 2014 §6"},
    # Layer 4: Enrichment/Biology
    {"id": "en01", "layer": "Enrichment",
     "text": "up-DE-гены обогащены в hallmark-pathway P1",
     "params": {"set": "hallmark", "direction": "up", "test": "gsea"},
     "source": "Subramanian 2005 (GSEA)"},
    {"id": "en02", "layer": "Enrichment",
     "text": "down-DE-гены обогащены в hallmark-pathway P2",
     "params": {"set": "hallmark", "direction": "down", "test": "gsea"},
     "source": "Subramanian 2005"},
    {"id": "en03", "layer": "Enrichment",
     "text": "DE-гены обогащены в GO biological process категории X",
     "params": {"set": "GO", "namespace": "BP", "test": "fisher"},
     "source": "Ashburner 2000 (GO); Subramanian 2005"},
    {"id": "en04", "layer": "Enrichment",
     "text": "DE-гены формируют biological module в PPI-сети STRING",
     "params": {"network": "STRING", "test": "module_enrichment"},
     "source": "Szklarczyk 2019 (STRING)"},
    {"id": "en05", "layer": "Enrichment",
     "text": "обогащённый pathway соответствует биологическому контексту эксперимента",
     "params": {"validation": "literature"},
     "source": "Conesa 2016 §7"},
]

RNASEQ_INTER_LAYER_EDGES = [
    # QC → Alignment
    ("qc01", "al01", "alignment rate осмыслен только для качественных reads"),
    ("qc02", "al01", "GC-bias искажает mapping success"),
    ("qc03", "al01", "адаптеры в reads снижают уникальное mapping"),
    # Alignment → Counting
    ("al01", "ct01", "counts требуют картированных reads"),
    ("al01", "ct02", "exonic-rate операционно вычислим только после alignment"),
    ("al02", "ct01", "сплайс-junctions нужны для счёта exonic reads"),
    ("al03", "ct01", "rRNA-контаминация смещает counting в пользу rRNA-генов"),
    # Counting → DE
    ("ct01", "de01", "DE-анализ требует матрицы счётов с ненулевым покрытием"),
    ("ct01", "de04", "VST/rlog работает на матрице счётов"),
    ("ct02", "de01", "корректное counting предусловие DE-теста"),
    ("de04", "de05", "PCA выполняется на VST/rlog-нормализованных данных"),
    # DE → Enrichment
    ("de02", "en01", "GSEA по up-DE требует up-DE-set"),
    ("de03", "en02", "GSEA по down-DE требует down-DE-set"),
    ("de01", "en03", "GO-обогащение оперирует на множестве DE-генов"),
    ("de01", "en04", "STRING-module enrichment требует DE-list"),
    ("en01", "en05", "литературная валидация поверх pathway-обогащения"),
    ("en03", "en05", "литературная валидация поверх GO-обогащения"),
]


# === airrflow === 15 узлов, 5 слоёв ===
AIRRFLOW_HYP = [
    # Layer 0: QC
    {"id": "qc01", "layer": "QC",
     "text": "Q30-base-quality для UMI- и V-segment reads ≥ 95%",
     "params": {"q_threshold": 30, "scope": "umi_and_v"},
     "source": "Andrews 2010 (FastQC)"},
    {"id": "qc02", "layer": "QC",
     "text": "UMI-длина однородна (CV < 0.05)",
     "params": {"cv_thr": 0.05, "metric": "umi_length"},
     "source": "Vander Heiden 2014 (pRESTO §2)"},
    {"id": "qc03", "layer": "QC",
     "text": "primer-распознавание ≥ 90% reads",
     "params": {"primer_match_rate": 0.90},
     "source": "Vander Heiden 2014 §2"},
    # Layer 1: Assembly
    {"id": "as01", "layer": "Assembly",
     "text": "≥ 80% UMI имеют ≥ 2 reads (надёжный консенсус)",
     "params": {"umi_min_reads": 2, "umi_coverage_rate": 0.80},
     "source": "Vander Heiden 2014 §3"},
    {"id": "as02", "layer": "Assembly",
     "text": "> 70% reads складываются в полные V-(D-)J-цепи",
     "params": {"assembly_rate": 0.70, "chain_completeness": "full"},
     "source": "Vander Heiden 2014"},
    # Layer 2: VDJ-annotation
    {"id": "vdj01", "layer": "VDJ",
     "text": "V-segment назначается с e-value < 1e-10 для ≥ 90% цепей",
     "params": {"evalue_thr": 1e-10, "segment": "V", "coverage": 0.90},
     "source": "Ye 2013 (IgBLAST)"},
    {"id": "vdj02", "layer": "VDJ",
     "text": "J-segment назначается для ≥ 95% цепей",
     "params": {"segment": "J", "coverage": 0.95},
     "source": "Ye 2013"},
    {"id": "vdj03", "layer": "VDJ",
     "text": "D-segment назначается для ≥ 60% IGH-цепей",
     "params": {"segment": "D", "coverage": 0.60, "locus": "IGH"},
     "source": "Ye 2013"},
    {"id": "vdj04", "layer": "VDJ",
     "text": "обнаружено ≥ 10 unique CDR3-клонотипов на образец",
     "params": {"min_unique_cdr3": 10},
     "source": "Yaari & Kleinstein 2015 §3"},
    # Layer 3: Clonal
    {"id": "cl01", "layer": "Clonal",
     "text": "∃ доминантная клонотипа с частотой > 5%",
     "params": {"frequency_thr": 0.05, "type": "dominant"},
     "source": "Yaari 2015 §4"},
    {"id": "cl02", "layer": "Clonal",
     "text": "частоты клонотипов следуют power-law (slope ∈ [-2, -1])",
     "params": {"distribution": "power_law", "slope_range": [-2, -1]},
     "source": "Yaari 2015 §4"},
    {"id": "cl03", "layer": "Clonal",
     "text": "индекс разнообразия Shannon H ≥ 5",
     "params": {"shannon_min": 5.0, "metric": "diversity"},
     "source": "Yaari 2015 §5"},
    # Layer 4: Repertoire-comparison
    {"id": "rc01", "layer": "Repertoire",
     "text": "частота V-гена IGHV1-69 различается между условиями (p<0.05)",
     "params": {"gene": "IGHV1-69", "test": "fisher", "p_thr": 0.05},
     "source": "Friedensohn 2017"},
    {"id": "rc02", "layer": "Repertoire",
     "text": "JSD-расстояние repertoire A vs B превышает background-distribution",
     "params": {"metric": "jensen_shannon", "comparison": "AvsB"},
     "source": "Friedensohn 2017"},
    {"id": "rc03", "layer": "Repertoire",
     "text": "доминантные клонотипы в условии A эволюционно связаны (lineage tree)",
     "params": {"analysis": "lineage_tree", "condition": "A"},
     "source": "Yaari 2015 §6"},
]

AIRRFLOW_INTER_LAYER_EDGES = [
    # QC → Assembly
    ("qc01", "as01", "консенсус UMI требует качественных reads"),
    ("qc02", "as01", "однородная UMI-длина необходима для группировки в консенсус"),
    ("qc03", "as02", "primer-распознавание определяет границы сборки V-(D-)J"),
    # Assembly internal: UMI-консенсус — pre-condition для полной сборки
    ("as01", "as02", "полная V-(D-)J-сборка строится на UMI-консенсус-группах"),
    # Assembly → VDJ
    ("as02", "vdj01", "V-аннотация работает на полных собранных цепях"),
    ("as02", "vdj02", "J-аннотация требует полной цепи"),
    ("as02", "vdj03", "D-аннотация требует полной цепи IGH"),
    # VDJ → Clonal
    ("vdj01", "vdj04", "уникальные CDR3 требуют V-аннотации"),
    ("vdj02", "vdj04", "уникальные CDR3 требуют J-аннотации"),
    ("vdj03", "vdj04", "D-аннотация участвует в~CDR3-определении IGH"),
    ("vdj04", "cl01", "доминантная клонотипа определяется на множестве CDR3"),
    ("vdj04", "cl02", "распределение частот опирается на ансамбль CDR3"),
    ("vdj04", "cl03", "Shannon-разнообразие считается по CDR3-репертуару"),
    # Clonal → Repertoire-comparison
    ("vdj01", "rc01", "сравнение V-генов требует надёжной V-аннотации"),
    ("cl02", "rc02", "JSD сравнивает распределения частот клонотипов"),
    ("cl01", "rc03", "lineage tree строится для доминантных клонотипов"),
    ("cl03", "rc02", "сравнение по разнообразию требует Shannon-индекса"),
]


# === sarek === 17 узлов, 5 слоёв ===
SAREK_HYP = [
    # Layer 0: QC
    {"id": "qc01", "layer": "QC",
     "text": "Q30 ≥ 30 на позициях 5'–30' для FASTQ-ridов",
     "params": {"q_threshold": 30, "pos_range": "5-30"},
     "source": "Andrews 2010 (FastQC)"},
    {"id": "qc02", "layer": "QC",
     "text": "доля адаптерной контаминации < 5%",
     "params": {"contamination_thr": 0.05, "type": "adapter"},
     "source": "Cutadapt; Conesa 2016"},
    {"id": "qc03", "layer": "QC",
     "text": "образцы tumor и normal содержат достаточно reads (≥30M на образец)",
     "params": {"min_reads_per_sample": 30_000_000, "sample_kinds": ["tumor", "normal"]},
     "source": "Van der Auwera 2020 (GATK best practices)"},
    # Layer 1: Alignment
    {"id": "al01", "layer": "Alignment",
     "text": "≥ 90% reads картируются BWA-MEM на референс GRCh38",
     "params": {"map_rate": 0.90, "reference": "GRCh38", "aligner": "bwa-mem"},
     "source": "Li 2013 (BWA-MEM); Van der Auwera 2020"},
    {"id": "al02", "layer": "Alignment",
     "text": "duplicate-rate < 30% после MarkDuplicates",
     "params": {"duplicate_thr": 0.30},
     "source": "Picard MarkDuplicates"},
    {"id": "al03", "layer": "Alignment",
     "text": "среднее покрытие WGS ≥ 30× для tumor и ≥ 30× для normal",
     "params": {"min_coverage": 30, "applies_to": ["tumor", "normal"]},
     "source": "Koboldt 2020 (somatic variant calling guidelines)"},
    # Layer 2: Base recalibration
    {"id": "bq01", "layer": "BQSR",
     "text": "Base Quality Score Recalibration сходится (дельта Q < 5)",
     "params": {"delta_q_max": 5, "tool": "GATK_BQSR"},
     "source": "Van der Auwera 2020"},
    {"id": "bq02", "layer": "BQSR",
     "text": "ApplyBQSR сохраняет coverage в пределах 5%",
     "params": {"coverage_drift_thr": 0.05},
     "source": "Van der Auwera 2020"},
    # Layer 3: Variant calling
    {"id": "vc01", "layer": "VariantCall",
     "text": "∃ соматические SNV (tumor-only, PASS-фильтр Mutect2)",
     "params": {"variant_type": "SNV", "filter": "PASS", "caller": "Mutect2"},
     "source": "Cibulskis 2013 (MuTect)"},
    {"id": "vc02", "layer": "VariantCall",
     "text": "∃ соматические Indels (≥ 1 bp)",
     "params": {"variant_type": "INDEL", "filter": "PASS"},
     "source": "Cibulskis 2013"},
    {"id": "vc03", "layer": "VariantCall",
     "text": "Ti/Tv-ratio ∈ [2.0, 2.2] для germline-variant-set",
     "params": {"ti_tv_range": [2.0, 2.2], "variant_kind": "germline"},
     "source": "Wang 2015 (variant QC)"},
    {"id": "vc04", "layer": "VariantCall",
     "text": "доля VAF < 0.05 для соматических вариантов",
     "params": {"vaf_thr": 0.05, "variant_kind": "somatic"},
     "source": "Cibulskis 2013"},
    # Layer 4: Annotation/Filter
    {"id": "an01", "layer": "Annotation",
     "text": "соматические варианты аннотируются VEP/ENSEMBL",
     "params": {"annotator": "VEP", "db": "ENSEMBL"},
     "source": "McLaren 2016 (VEP)"},
    {"id": "an02", "layer": "Annotation",
     "text": "∃ варианты в driver-генах из COSMIC CGC",
     "params": {"db": "COSMIC_CGC", "gene_set": "driver"},
     "source": "Sondka 2018 (COSMIC)"},
    {"id": "an03", "layer": "Annotation",
     "text": "∃ варианты с высоким impact (HIGH или MODERATE)",
     "params": {"impact": ["HIGH", "MODERATE"]},
     "source": "McLaren 2016"},
    {"id": "an04", "layer": "Annotation",
     "text": "доля variants в Tier-1 COSMIC > 0",
     "params": {"db": "COSMIC", "tier": 1},
     "source": "Sondka 2018"},
    {"id": "an05", "layer": "Annotation",
     "text": "распределение мутационной нагрузки (TMB) выше cutoff чувствительности к ICI",
     "params": {"metric": "TMB", "cutoff": 10},
     "source": "Chalmers 2017 (TMB)"},
]

SAREK_INTER_LAYER_EDGES = [
    ("qc01", "al01", "alignment требует качественных reads"),
    ("qc02", "al01", "адаптеры снижают mapping rate"),
    ("qc03", "al03", "необходимый объём reads для глубины покрытия"),
    ("al01", "al02", "duplicate-rate считается на mapped reads"),
    ("al01", "al03", "глубина покрытия измеряется на mapped reads"),
    ("al02", "bq01", "BQSR работает на dedup BAM"),
    ("bq01", "bq02", "ApplyBQSR — следующий шаг после BQSR-калибровки"),
    ("bq02", "vc01", "variant calling требует recalibrated BAM"),
    ("bq02", "vc02", "variant calling требует recalibrated BAM"),
    ("vc01", "vc03", "Ti/Tv считается на set SNV"),
    ("vc01", "vc04", "VAF осмыслен для соматических SNV"),
    ("vc01", "an01", "annotation работает на VCF после calling"),
    ("vc02", "an01", "annotation работает на VCF после calling"),
    ("an01", "an02", "driver-обнаружение опирается на аннотированный VCF"),
    ("an01", "an03", "impact-классификация — часть VEP"),
    ("an02", "an04", "Tier-1 COSMIC — подмножество CGC-генов"),
    ("an03", "an05", "TMB считается на варианты с impact"),
]


# === atacseq === 14 узлов, 5 слоёв ===
ATACSEQ_HYP = [
    # Layer 0: QC
    {"id": "qc01", "layer": "QC",
     "text": "Q30 ≥ 30 на позициях 5'–30'",
     "params": {"q_threshold": 30},
     "source": "Andrews 2010"},
    {"id": "qc02", "layer": "QC",
     "text": "доля reads в mitochondrial-регионе < 20%",
     "params": {"mito_rate_thr": 0.20},
     "source": "Yan 2020 (ATAC-seq QC)"},
    {"id": "qc03", "layer": "QC",
     "text": "TSS-enrichment score ≥ 7 (для эукариот)",
     "params": {"tss_enrichment_thr": 7.0},
     "source": "ENCODE ATAC-seq guidelines"},
    # Layer 1: Alignment
    {"id": "al01", "layer": "Alignment",
     "text": "≥ 80% reads картируются BWA-MEM",
     "params": {"map_rate": 0.80, "aligner": "bwa-mem"},
     "source": "Li 2013"},
    {"id": "al02", "layer": "Alignment",
     "text": "доля reads в blacklist-регионах < 5%",
     "params": {"blacklist_rate": 0.05},
     "source": "ENCODE blacklist; Amemiya 2019"},
    {"id": "al03", "layer": "Alignment",
     "text": "fragment-size distribution имеет характерный nucleosomal pattern",
     "params": {"check": "fragment_periodicity"},
     "source": "Buenrostro 2013 (ATAC-seq)"},
    # Layer 2: Peak calling
    {"id": "pk01", "layer": "Peaks",
     "text": "∃ MACS2 narrowPeaks (q<0.01) ≥ 10000 на образец",
     "params": {"caller": "MACS2", "qvalue": 0.01, "min_peaks": 10000},
     "source": "Zhang 2008 (MACS)"},
    {"id": "pk02", "layer": "Peaks",
     "text": "FRiP (Fraction of Reads in Peaks) ≥ 0.20",
     "params": {"frip_thr": 0.20},
     "source": "ENCODE quality metrics"},
    {"id": "pk03", "layer": "Peaks",
     "text": "consensus peak set между реплкиами имеет ≥ 70% overlap",
     "params": {"replicate_overlap_thr": 0.70},
     "source": "Yan 2020"},
    # Layer 3: Differential accessibility
    {"id": "da01", "layer": "DiffAcc",
     "text": "∃ differentially accessible peaks (DESeq2 на counts, FDR<0.05)",
     "params": {"fdr": 0.05, "tool": "DESeq2"},
     "source": "Love 2014; Yan 2020"},
    {"id": "da02", "layer": "DiffAcc",
     "text": "∃ gained-accessibility peaks (log2FC > 1, FDR<0.05)",
     "params": {"fdr": 0.05, "tool": "DESeq2", "lfc_thr": 1.0,
                "direction": "gained"},
     "source": "subsumption(da01)"},
    # Layer 4: Motif / Biology
    {"id": "mt01", "layer": "Motif",
     "text": "∃ обогащённые TF-мотивы в DA-peaks (HOMER, p<1e-5)",
     "params": {"tool": "HOMER", "p_thr": 1e-5},
     "source": "Heinz 2010 (HOMER)"},
    {"id": "mt02", "layer": "Motif",
     "text": "обогащённые TF-мотивы перекрываются с ChIP-Atlas для соответствующего ткани",
     "params": {"reference": "ChIP-Atlas"},
     "source": "Oki 2018"},
    {"id": "mt03", "layer": "Motif",
     "text": "DA-peaks ассоциируются с регуляторными элементами (enhancer/promoter)",
     "params": {"annotation": "ChromHMM", "elements": ["enhancer", "promoter"]},
     "source": "Ernst 2011 (ChromHMM)"},
]

ATACSEQ_INTER_LAYER_EDGES = [
    ("qc01", "al01", "mapping требует качественных reads"),
    ("qc02", "al03", "fragment-distribution считается после очистки от mito"),
    ("qc03", "pk01", "TSS-enrichment мотивирует peak calling в TSS"),
    ("al01", "pk01", "peaks определяются на mapped reads"),
    ("al02", "pk01", "blacklist filtering предусловие peak calling"),
    ("al03", "pk01", "nucleosomal fragments — основа ATAC-сигнала"),
    ("pk01", "pk02", "FRiP считается с use peak-set"),
    ("pk01", "pk03", "consensus считается через peak-sets реплкиаций"),
    ("pk03", "da01", "DA анализ работает на consensus peak set"),
    ("pk02", "da01", "FRiP — предусловие воспроизводимости"),
    ("da01", "mt01", "motif-обогащение анализирует DA-peaks"),
    ("mt01", "mt02", "TF-валидация через ChIP-Atlas работает на мотивах"),
    ("da01", "mt03", "регуляторная аннотация работает на DA-peaks"),
]


# === chipseq === 13 узлов, 5 слоёв ===
CHIPSEQ_HYP = [
    # Layer 0: QC
    {"id": "qc01", "layer": "QC",
     "text": "Q30 ≥ 30 на позициях 5'–30'",
     "params": {"q_threshold": 30},
     "source": "Andrews 2010"},
    {"id": "qc02", "layer": "QC",
     "text": "≥ 20M reads на образец (ChIP + input)",
     "params": {"min_reads": 20_000_000, "sample_kinds": ["chip", "input"]},
     "source": "Bailey 2013 (ENCODE ChIP-seq)"},
    {"id": "qc03", "layer": "QC",
     "text": "доля duplicate-reads < 30%",
     "params": {"duplicate_thr": 0.30},
     "source": "Bailey 2013"},
    # Layer 1: Alignment
    {"id": "al01", "layer": "Alignment",
     "text": "≥ 80% reads уникально картируются",
     "params": {"unique_map_rate": 0.80},
     "source": "Bailey 2013"},
    {"id": "al02", "layer": "Alignment",
     "text": "доля reads в blacklist < 5%",
     "params": {"blacklist_rate": 0.05},
     "source": "Amemiya 2019"},
    # Layer 2: Peak calling
    {"id": "pk01", "layer": "Peaks",
     "text": "∃ MACS2 peaks (q<0.01) ≥ 5000",
     "params": {"caller": "MACS2", "qvalue": 0.01, "min_peaks": 5000},
     "source": "Zhang 2008"},
    {"id": "pk02", "layer": "Peaks",
     "text": "FRiP ≥ 0.05 (для TF), ≥ 0.30 (для гистоновых модификаций)",
     "params": {"frip_min_tf": 0.05, "frip_min_hm": 0.30},
     "source": "ENCODE; Landt 2012"},
    {"id": "pk03", "layer": "Peaks",
     "text": "консенсус peak-set между реплкиаций ≥ 60% overlap",
     "params": {"replicate_overlap_thr": 0.60},
     "source": "Landt 2012"},
    # Layer 3: Differential binding
    {"id": "db01", "layer": "DiffBind",
     "text": "∃ differentially bound peaks (DiffBind, FDR<0.05)",
     "params": {"fdr": 0.05, "tool": "DiffBind"},
     "source": "Ross-Innes 2012 (DiffBind)"},
    {"id": "db02", "layer": "DiffBind",
     "text": "∃ gain-of-binding peaks (log2FC > 1)",
     "params": {"fdr": 0.05, "tool": "DiffBind", "lfc_thr": 1.0,
                "direction": "gain"},
     "source": "subsumption(db01)"},
    # Layer 4: Motif / Biology
    {"id": "mt01", "layer": "Motif",
     "text": "обогащённые TF-мотивы в peak-set (MEME, p<1e-5)",
     "params": {"tool": "MEME", "p_thr": 1e-5},
     "source": "Bailey 2011 (MEME)"},
    {"id": "mt02", "layer": "Motif",
     "text": "обогащённый мотив соответствует канонической PWM из JASPAR",
     "params": {"db": "JASPAR", "match_score": 0.85},
     "source": "Castro-Mondragon 2022 (JASPAR)"},
    {"id": "mt03", "layer": "Motif",
     "text": "DB-peaks обогащены в проксимальных промоторах",
     "params": {"region": "promoter", "max_distance_kb": 2},
     "source": "Bailey 2013"},
]

CHIPSEQ_INTER_LAYER_EDGES = [
    ("qc01", "al01", "mapping требует качественных reads"),
    ("qc02", "pk01", "достаточное число reads для peak detection"),
    ("qc03", "pk01", "low-duplicate set нужен для накопления сигнала"),
    ("al01", "pk01", "peaks определяются на mapped reads"),
    ("al02", "pk01", "blacklist filtering — предусловие"),
    ("pk01", "pk02", "FRiP считается с use peak-set"),
    ("pk01", "pk03", "consensus считается через replicates"),
    ("pk03", "db01", "DB анализ работает на consensus peak set"),
    ("db01", "mt01", "motif-обогащение анализирует DB-peaks"),
    ("mt01", "mt02", "PWM-валидация работает на мотивах"),
    ("db01", "mt03", "promoter-аннотация анализирует DB-peaks"),
]


# === methylseq === 15 узлов, 5 слоёв ===
METHYLSEQ_HYP = [
    {"id": "qc01", "layer": "QC",
     "text": "Q30 ≥ 30 на позициях 5'–30' bisulfite reads",
     "params": {"q_threshold": 30, "pos_range": "5-30"},
     "source": "Andrews 2010 (FastQC); Krueger 2011 (Bismark)"},
    {"id": "qc02", "layer": "QC",
     "text": "bisulfite conversion rate ≥ 99% (по неметилированному lambda-контролю)",
     "params": {"conversion_rate_thr": 0.99, "control": "lambda_DNA"},
     "source": "Krueger 2011"},
    {"id": "qc03", "layer": "QC",
     "text": "доля адаптерной контаминации < 5%",
     "params": {"contamination_thr": 0.05, "type": "adapter"},
     "source": "Martin 2011 (Cutadapt)"},
    {"id": "al01", "layer": "Alignment",
     "text": "≥ 60% reads картируются Bismark на bisulfite-конвертированный референс",
     "params": {"map_rate": 0.60, "aligner": "bismark"},
     "source": "Krueger 2011"},
    {"id": "al02", "layer": "Alignment",
     "text": "доля duplicate-reads < 25% после deduplication",
     "params": {"duplicate_thr": 0.25},
     "source": "Picard MarkDuplicates"},
    {"id": "al03", "layer": "Alignment",
     "text": "среднее покрытие CpG ≥ 10× в анализируемых регионах",
     "params": {"min_coverage": 10, "context": "CpG"},
     "source": "Ziller 2015 (WGBS guidelines)"},
    {"id": "mc01", "layer": "MethCalling",
     "text": "глобальный уровень метилирования CpG в ожидаемом диапазоне [0,4;0,8]",
     "params": {"global_meth_range": [0.4, 0.8], "context": "CpG"},
     "source": "Ziller 2015"},
    {"id": "mc02", "layer": "MethCalling",
     "text": "CHH/CHG-метилирование < 5% (у млекопитающих)",
     "params": {"non_cpg_thr": 0.05, "organism_class": "mammal"},
     "source": "Ziller 2015"},
    {"id": "mc03", "layer": "MethCalling",
     "text": "распределение метилирования бимодально (peaks at 0 and 1)",
     "params": {"distribution": "bimodal"},
     "source": "Ziller 2015"},
    {"id": "dm01", "layer": "DMR",
     "text": "∃ дифференциально метилированные регионы (методом methylKit, q<0.01)",
     "params": {"qvalue": 0.01, "tool": "methylKit", "scope": "region"},
     "source": "Akalin 2012 (methylKit)"},
    {"id": "dm02", "layer": "DMR",
     "text": "∃ hyper-метилированные DMR (∆meth > 25%)",
     "params": {"qvalue": 0.01, "tool": "methylKit", "delta_meth": 0.25,
                "direction": "hyper"},
     "source": "Akalin 2012; subsumption(dm01)"},
    {"id": "dm03", "layer": "DMR",
     "text": "∃ hypo-метилированные DMR (∆meth > 25%)",
     "params": {"qvalue": 0.01, "tool": "methylKit", "delta_meth": 0.25,
                "direction": "hypo"},
     "source": "Akalin 2012; subsumption(dm01)"},
    {"id": "bi01", "layer": "Biology",
     "text": "DMR обогащены в CpG-островках и shores",
     "params": {"feature": "cpg_island", "test": "fisher"},
     "source": "Irizarry 2009 (CpG shores)"},
    {"id": "bi02", "layer": "Biology",
     "text": "DMR ассоциированы с регуляторными элементами (enhancer/promoter)",
     "params": {"annotation": "ChromHMM", "elements": ["enhancer", "promoter"]},
     "source": "Ernst 2011 (ChromHMM)"},
    {"id": "bi03", "layer": "Biology",
     "text": "DMR-связанные гены обогащены в GO biological process",
     "params": {"set": "GO", "namespace": "BP", "test": "fisher"},
     "source": "Ashburner 2000 (GO)"},
]

METHYLSEQ_INTER_LAYER_EDGES = [
    ("qc01", "al01", "alignment требует качественных reads"),
    ("qc02", "mc01", "оценка метилирования зависит от bisulfite-conversion"),
    ("qc03", "al01", "адаптерные хвосты снижают mapping"),
    ("al01", "al02", "duplicate-rate на mapped reads"),
    ("al01", "al03", "глубина покрытия — после mapping"),
    ("al03", "mc01", "оценка глобального уровня требует покрытия CpG"),
    ("mc01", "mc02", "non-CpG считается на той же глубине"),
    ("mc01", "mc03", "бимодальность — свойство per-CpG-распределения"),
    ("mc01", "dm01", "DMR-вызов требует per-CpG meth-уровней"),
    ("mc03", "dm01", "корректное распределение — предпосылка DMR-теста"),
    ("dm01", "bi01", "CpG-island enrichment — анализ DMR-set"),
    ("dm01", "bi02", "регуляторная аннотация — анализ DMR-set"),
    ("dm02", "bi03", "GO-обогащение по hyper-DMR-генам"),
    ("dm03", "bi03", "GO-обогащение по hypo-DMR-генам"),
    ("bi02", "bi03", "регуляторная категоризация поддерживает GO-интерпретацию"),
]


# === hic === 15 узлов, 5 слоёв ===
HIC_HYP = [
    {"id": "qc01", "layer": "QC",
     "text": "Q30 ≥ 30 на reads",
     "params": {"q_threshold": 30},
     "source": "Andrews 2010"},
    {"id": "qc02", "layer": "QC",
     "text": "доля valid pairs ≥ 50% (после фильтрации ligation artefacts)",
     "params": {"valid_pair_rate": 0.50},
     "source": "Belaghzal 2017 (Hi-C QC)"},
    {"id": "qc03", "layer": "QC",
     "text": "cis/trans-ratio ≥ 2 (преобладание внутрихромосомных контактов)",
     "params": {"cis_trans_ratio_thr": 2.0},
     "source": "Lieberman-Aiden 2009 (Hi-C)"},
    {"id": "al01", "layer": "Alignment",
     "text": "≥ 70% pairs картируются на референс",
     "params": {"map_rate": 0.70},
     "source": "Servant 2015 (HiC-Pro)"},
    {"id": "al02", "layer": "Alignment",
     "text": "self-circles и dangling-ends исключены",
     "params": {"filter": ["self_circle", "dangling_end"]},
     "source": "Servant 2015"},
    {"id": "al03", "layer": "Alignment",
     "text": "уникальные ligation events ≥ 100M на образец",
     "params": {"min_unique_pairs": 100_000_000},
     "source": "Belaghzal 2017"},
    {"id": "cm01", "layer": "ContactMatrix",
     "text": "матрица контактов нормирована ICE-методом",
     "params": {"normalization": "ICE"},
     "source": "Imakaev 2012 (ICE)"},
    {"id": "cm02", "layer": "ContactMatrix",
     "text": "decay контактов с расстоянием соответствует степенному закону",
     "params": {"decay": "power_law"},
     "source": "Lieberman-Aiden 2009"},
    {"id": "cm03", "layer": "ContactMatrix",
     "text": "разрешение матрицы 10 kb с покрытием ≥ 80% bins",
     "params": {"resolution_bp": 10000, "bin_coverage_rate": 0.80},
     "source": "Rao 2014 (in situ Hi-C)"},
    {"id": "co01", "layer": "Compartments",
     "text": "∃ A/B-компартменты (PC1-знак из ковариационной матрицы)",
     "params": {"method": "PCA", "axis": 1},
     "source": "Lieberman-Aiden 2009"},
    {"id": "co02", "layer": "Compartments",
     "text": "∃ TADs (insulation-score, размер 0,1–1 Mb)",
     "params": {"method": "insulation", "size_range_mb": [0.1, 1.0]},
     "source": "Dixon 2012 (TADs)"},
    {"id": "co03", "layer": "Compartments",
     "text": "A-компартмент обогащён активным хроматином (H3K27ac)",
     "params": {"compartment": "A", "mark": "H3K27ac"},
     "source": "Lieberman-Aiden 2009"},
    {"id": "lp01", "layer": "Loops",
     "text": "∃ chromatin loops (HICCUPS, FDR<0.10)",
     "params": {"caller": "HICCUPS", "fdr": 0.10},
     "source": "Rao 2014"},
    {"id": "lp02", "layer": "Loops",
     "text": "loop-anchors обогащены CTCF-сайтами",
     "params": {"feature": "CTCF_site", "test": "enrichment"},
     "source": "Rao 2014"},
    {"id": "lp03", "layer": "Loops",
     "text": "loop-anchors имеют конвергентную CTCF-ориентацию",
     "params": {"feature": "CTCF_orientation", "expected": "convergent"},
     "source": "Rao 2014"},
]

HIC_INTER_LAYER_EDGES = [
    ("qc01", "al01", "alignment требует качественных reads"),
    ("qc02", "al02", "valid-pair фильтрация удаляет artefacts"),
    ("qc03", "cm01", "cis-преобладание необходимо для матрицы внутрихромосомных контактов"),
    ("al01", "al02", "фильтрация ligation events работает на mapped pairs"),
    ("al02", "al03", "уникальные pairs — после фильтров"),
    ("al03", "cm01", "ICE-нормировка требует достаточного объёма pairs"),
    ("cm01", "cm02", "decay измеряется на нормированной матрице"),
    ("cm01", "cm03", "bin-разрешение зависит от глубины"),
    ("cm03", "co01", "PCA для компартментов на матрице с целевым разрешением"),
    ("co01", "co02", "TAD-структура внутри компартментов"),
    ("co01", "co03", "обогащение mark'ом — свойство компартмента"),
    ("co02", "lp01", "loops обычно лежат внутри TAD-границ"),
    ("lp01", "lp02", "CTCF-обогащение по loop-anchors"),
    ("lp02", "lp03", "ориентация CTCF — свойство обнаруженных сайтов"),
    ("co02", "lp03", "TAD-границы — преимущественно конвергентные CTCF"),
]


# === ampliseq === 16 узлов, 5 слоёв ===
AMPLISEQ_HYP = [
    {"id": "qc01", "layer": "QC",
     "text": "Q30 ≥ 30 на позициях 5'–30' амплпиконных reads",
     "params": {"q_threshold": 30, "pos_range": "5-30"},
     "source": "Andrews 2010"},
    {"id": "qc02", "layer": "QC",
     "text": "длина reads соответствует ожидаемому амплпикону",
     "params": {"length_target_bp": 250, "tol_bp": 25},
     "source": "Callahan 2016 (DADA2)"},
    {"id": "qc03", "layer": "QC",
     "text": "primer-распознавание ≥ 90% reads",
     "params": {"primer_match_rate": 0.90},
     "source": "Bolyen 2019 (QIIME2)"},
    {"id": "dn01", "layer": "Denoising",
     "text": "DADA2 выдаёт ≥ 100 уникальных ASV на образец",
     "params": {"min_asv_per_sample": 100, "tool": "DADA2"},
     "source": "Callahan 2016"},
    {"id": "dn02", "layer": "Denoising",
     "text": "доля chimera-reads < 5% после chimera-removal",
     "params": {"chimera_rate_thr": 0.05},
     "source": "Callahan 2016 §4"},
    {"id": "dn03", "layer": "Denoising",
     "text": "rarefaction-кривая выходит на плато для ≥ 80% образцов",
     "params": {"plateau_sample_rate": 0.80},
     "source": "Bolyen 2019"},
    {"id": "tx01", "layer": "Taxonomy",
     "text": "≥ 80% ASV получают taxonomy-присвоение на уровне рода",
     "params": {"min_classified_rate": 0.80, "level": "genus", "db": "SILVA"},
     "source": "Quast 2013 (SILVA)"},
    {"id": "tx02", "layer": "Taxonomy",
     "text": "≥ 60% ASV получают присвоение на уровне вида",
     "params": {"min_classified_rate": 0.60, "level": "species"},
     "source": "Quast 2013"},
    {"id": "tx03", "layer": "Taxonomy",
     "text": "phyla-распределение согласуется с типом образца (e.g. gut: Bacteroidetes+Firmicutes ≥ 60%)",
     "params": {"sample_type": "gut", "expected_phyla_sum": 0.60},
     "source": "Human Microbiome Project Consortium 2012"},
    {"id": "dv01", "layer": "Diversity",
     "text": "Shannon-разнообразие H' ∈ [2, 6]",
     "params": {"shannon_range": [2, 6]},
     "source": "Magurran 2004"},
    {"id": "dv02", "layer": "Diversity",
     "text": "α-разнообразие различается между группами (Kruskal-Wallis, p<0.05)",
     "params": {"test": "kruskal_wallis", "p_thr": 0.05, "scope": "alpha"},
     "source": "Bolyen 2019"},
    {"id": "dv03", "layer": "Diversity",
     "text": "β-разнообразие разделяет группы (PERMANOVA на UniFrac, p<0.05)",
     "params": {"metric": "UniFrac", "test": "PERMANOVA", "p_thr": 0.05},
     "source": "Lozupone 2005 (UniFrac); Anderson 2001 (PERMANOVA)"},
    {"id": "da01", "layer": "DiffAbundance",
     "text": "∃ дифференциально представленные ASV/таксоны (ANCOM-BC, q<0.05)",
     "params": {"tool": "ANCOM-BC", "qvalue": 0.05},
     "source": "Lin 2020 (ANCOM-BC)"},
    {"id": "da02", "layer": "DiffAbundance",
     "text": "∃ up-представленные таксоны в группе A (LFC > 1)",
     "params": {"tool": "ANCOM-BC", "qvalue": 0.05, "lfc_thr": 1.0,
                "direction": "up"},
     "source": "Lin 2020; subsumption(da01)"},
    {"id": "da03", "layer": "DiffAbundance",
     "text": "∃ down-представленные таксоны в группе A (LFC < -1)",
     "params": {"tool": "ANCOM-BC", "qvalue": 0.05, "lfc_thr": 1.0,
                "direction": "down"},
     "source": "Lin 2020; subsumption(da01)"},
    {"id": "da04", "layer": "DiffAbundance",
     "text": "дифференциальные таксоны согласуются с клинической метаданной",
     "params": {"correlation": "spearman", "p_thr": 0.05},
     "source": "Bolyen 2019"},
]

AMPLISEQ_INTER_LAYER_EDGES = [
    ("qc01", "dn01", "DADA2 требует качественных reads"),
    ("qc02", "dn01", "длина читов согласована с амплпиконом"),
    ("qc03", "dn01", "primer-удаление — pre-condition для denoising"),
    ("dn01", "dn02", "chimera-removal работает на множестве ASV"),
    ("dn02", "dn03", "rarefaction строится на post-chimera ASV-table"),
    ("dn01", "tx01", "taxonomy присваивается ASV"),
    ("tx01", "tx02", "вид-уровень классификации опирается на род-уровень"),
    ("tx01", "tx03", "phyla-сумма считается из присвоений"),
    ("dn03", "dv01", "Shannon-разнообразие на rarefied ASV-table"),
    ("tx01", "dv01", "альфа-разнообразие на классифицированных ASV"),
    ("dv01", "dv02", "групповое сравнение alpha опирается на индексы"),
    ("dv01", "dv03", "бета-разнообразие на тех же ASV-counts"),
    ("dn01", "da01", "DA-тест на ASV-counts"),
    ("tx01", "da01", "DA в терминах таксонов требует классификации"),
    ("da01", "da04", "связь с метаданной — финальная интерпретация"),
    ("dv02", "da04", "разделение групп подкрепляет DA-интерпретацию"),
]


# === mag === 16 узлов, 5 слоёв ===
MAG_HYP = [
    {"id": "qc01", "layer": "QC",
     "text": "Q30 ≥ 30 на метагеномных reads",
     "params": {"q_threshold": 30},
     "source": "Andrews 2010"},
    {"id": "qc02", "layer": "QC",
     "text": "доля host-reads после фильтрации < 5%",
     "params": {"host_residual_thr": 0.05},
     "source": "Langmead 2012 (Bowtie2 host-removal)"},
    {"id": "qc03", "layer": "QC",
     "text": "доля adapter-контаминации < 5%",
     "params": {"contamination_thr": 0.05},
     "source": "Martin 2011"},
    {"id": "as01", "layer": "Assembly",
     "text": "N50 метагеномной сборки (MEGAHIT/SPAdes) ≥ 5 kb",
     "params": {"n50_min_bp": 5000, "assembler": ["MEGAHIT", "metaSPAdes"]},
     "source": "Li 2015 (MEGAHIT); Nurk 2017 (metaSPAdes)"},
    {"id": "as02", "layer": "Assembly",
     "text": "≥ 70% reads картируются обратно на собранные контиги",
     "params": {"backmap_rate": 0.70},
     "source": "Sieber 2018"},
    {"id": "as03", "layer": "Assembly",
     "text": "общая длина контигов > 100 Mb для типичного gut-метагенома",
     "params": {"min_total_bp": 100_000_000, "sample_type": "gut"},
     "source": "Almeida 2019"},
    {"id": "bn01", "layer": "Binning",
     "text": "≥ 10 MAG бинов с completeness ≥ 50% (CheckM2)",
     "params": {"completeness_thr": 0.50, "tool": "CheckM2", "min_bins": 10},
     "source": "Chklovski 2023 (CheckM2)"},
    {"id": "bn02", "layer": "Binning",
     "text": "≥ 5 MAG бинов high-quality (≥90% complete, ≤5% contam)",
     "params": {"completeness_thr": 0.90, "contam_thr": 0.05, "min_bins": 5},
     "source": "Bowers 2017 (MIMAG); subsumption(bn01)"},
    {"id": "bn03", "layer": "Binning",
     "text": "консенсус-биннинг (DAS_Tool) увеличивает число HQ-MAG vs одиночные методы",
     "params": {"tool": "DAS_Tool"},
     "source": "Sieber 2018 (DAS_Tool)"},
    {"id": "tx01", "layer": "Taxonomy",
     "text": "≥ 80% HQ-MAG получают таксономию на уровне рода (GTDB-Tk)",
     "params": {"min_classified_rate": 0.80, "db": "GTDB", "level": "genus"},
     "source": "Chaumeil 2020 (GTDB-Tk)"},
    {"id": "tx02", "layer": "Taxonomy",
     "text": "≥ 30% MAG — потенциально новые виды (ANI < 95% к известным)",
     "params": {"novel_thr_ani": 0.95, "min_novel_rate": 0.30},
     "source": "Parks 2020 (GTDB)"},
    {"id": "tx03", "layer": "Taxonomy",
     "text": "phyla-композиция согласуется с reference (Bacteroidetes, Firmicutes >50%)",
     "params": {"expected_phyla": ["Bacteroidetes", "Firmicutes"]},
     "source": "Almeida 2019"},
    {"id": "fn01", "layer": "Function",
     "text": "≥ 70% генов получают KEGG/CAZyme-аннотацию",
     "params": {"min_annot_rate": 0.70, "db": ["KEGG", "CAZyme"]},
     "source": "Kanehisa 2017 (KEGG); Cantarel 2009 (CAZy)"},
    {"id": "fn02", "layer": "Function",
     "text": "∃ обогащение функциональных путей в условиях A vs B (FDR<0.05)",
     "params": {"test": "fisher", "fdr": 0.05, "scope": "pathway"},
     "source": "Kanehisa 2017"},
    {"id": "fn03", "layer": "Function",
     "text": "обнаружены MAG с antimicrobial resistance genes (CARD/AMRFinder)",
     "params": {"db": ["CARD", "AMRFinder"]},
     "source": "Alcock 2020 (CARD); Feldgarden 2021 (AMRFinder)"},
    {"id": "fn04", "layer": "Function",
     "text": "функциональные пути коррелируют с метаданной (Spearman, p<0.05)",
     "params": {"correlation": "spearman", "p_thr": 0.05},
     "source": "Almeida 2019"},
]

MAG_INTER_LAYER_EDGES = [
    ("qc01", "as01", "assembly требует качественных reads"),
    ("qc02", "as01", "host-removal — pre-condition для метагеномной сборки"),
    ("qc03", "as01", "адаптеры искажают сборку"),
    ("as01", "as02", "backmap считается на собранных контигах"),
    ("as01", "as03", "общая длина — статистика сборки"),
    ("as01", "bn01", "binning работает на контигах сборки"),
    ("as02", "bn01", "coverage из backmap — feature для binning"),
    ("bn01", "bn02", "HQ-подмножество — подмножество MQ"),
    ("bn01", "bn03", "консенсус улучшает результаты базовых методов"),
    ("bn02", "tx01", "GTDB-Tk запускается на HQ-MAG"),
    ("tx01", "tx02", "novelty-оценка по результатам классификации"),
    ("tx01", "tx03", "phyla-композиция — агрегация классификаций"),
    ("bn02", "fn01", "functional annotation на HQ-MAG"),
    ("fn01", "fn02", "путь-обогащение использует аннотированные гены"),
    ("fn01", "fn03", "AMR-поиск среди аннотированных"),
    ("fn02", "fn04", "связь путей с метаданной — финальная интерпретация"),
    ("tx02", "fn04", "новизна таксонов учитывается в метаданной-корреляциях"),
]


# === viralrecon === 15 узлов, 5 слоёв ===
VIRALRECON_HYP = [
    {"id": "qc01", "layer": "QC",
     "text": "Q30 ≥ 30 на reads амплпиконного/метагеномного протокола",
     "params": {"q_threshold": 30},
     "source": "Andrews 2010"},
    {"id": "qc02", "layer": "QC",
     "text": "доля host-reads после фильтрации < 10%",
     "params": {"host_residual_thr": 0.10},
     "source": "Langmead 2012"},
    {"id": "qc03", "layer": "QC",
     "text": "primer-trimming успешен ≥ 95% (для ARTIC-протокола)",
     "params": {"primer_trim_rate": 0.95, "protocol": "ARTIC"},
     "source": "Tyson 2020 (ARTIC)"},
    {"id": "al01", "layer": "Alignment",
     "text": "≥ 90% reads картируются на reference (SARS-CoV-2 MN908947.3)",
     "params": {"map_rate": 0.90, "reference": "MN908947.3"},
     "source": "Wu 2020"},
    {"id": "al02", "layer": "Alignment",
     "text": "среднее покрытие генома ≥ 100×",
     "params": {"min_coverage": 100},
     "source": "Tyson 2020"},
    {"id": "al03", "layer": "Alignment",
     "text": "≥ 95% генома покрыто ≥ 10× (breadth-coverage)",
     "params": {"breadth_thr_x10": 0.95},
     "source": "Tyson 2020"},
    {"id": "vc01", "layer": "VariantCall",
     "text": "∃ SNV относительно референса (iVar/LoFreq, AF ≥ 0.5)",
     "params": {"caller": ["iVar", "LoFreq"], "af_thr": 0.5,
                "variant_type": "SNV"},
     "source": "Grubaugh 2019 (iVar); Wilm 2012 (LoFreq)"},
    {"id": "vc02", "layer": "VariantCall",
     "text": "∃ Indels с AF ≥ 0.5",
     "params": {"af_thr": 0.5, "variant_type": "INDEL"},
     "source": "Grubaugh 2019"},
    {"id": "vc03", "layer": "VariantCall",
     "text": "доля low-frequency variants (AF<0.2) согласуется с background-noise",
     "params": {"af_thr_low": 0.2},
     "source": "Grubaugh 2019"},
    {"id": "cs01", "layer": "Consensus",
     "text": "консенсус-сборка покрывает ≥ 95% генома (без N)",
     "params": {"max_n_rate": 0.05},
     "source": "Tyson 2020"},
    {"id": "cs02", "layer": "Consensus",
     "text": "консенсус-геном проходит Nextclade QC",
     "params": {"tool": "Nextclade", "qc": "good"},
     "source": "Aksamentov 2021 (Nextclade)"},
    {"id": "cs03", "layer": "Consensus",
     "text": "линия Pango назначается с confidence",
     "params": {"tool": "Pangolin"},
     "source": "Rambaut 2020 (Pangolin)"},
    {"id": "ph01", "layer": "Phylogenetics",
     "text": "консенсус-геном размещён на reference-дереве (UShER/Nextstrain)",
     "params": {"tool": "UShER"},
     "source": "Turakhia 2021 (UShER)"},
    {"id": "ph02", "layer": "Phylogenetics",
     "text": "∃ filogenетически-значимые мутации в S-белке",
     "params": {"region": "Spike", "mutation_set": "S-protein"},
     "source": "Hodcroft 2021"},
    {"id": "ph03", "layer": "Phylogenetics",
     "text": "вариант ассоциирован с эпидемиологическим кластером по дате/геолокации",
     "params": {"metadata": ["date", "geo"], "test": "cluster_match"},
     "source": "Hadfield 2018 (Nextstrain)"},
]

VIRALRECON_INTER_LAYER_EDGES = [
    ("qc01", "al01", "mapping требует качественных reads"),
    ("qc02", "al01", "host-removal — pre-condition для viral-mapping"),
    ("qc03", "al02", "primer-trim определяет coverage uniformity"),
    ("al01", "al02", "coverage на mapped reads"),
    ("al02", "al03", "breadth-coverage из depth-distribution"),
    ("al02", "vc01", "variant calling требует адекватной глубины"),
    ("al03", "vc01", "calls на регионах с purpose-coverage"),
    ("vc01", "vc02", "indel-вызов параллелен SNV"),
    ("vc01", "vc03", "low-AF — спектр того же caller-output"),
    ("al03", "cs01", "consensus покрывает high-coverage регионы"),
    ("vc01", "cs01", "consensus инкорпорирует высокочастотные SNV"),
    ("cs01", "cs02", "Nextclade QC работает на consensus"),
    ("cs01", "cs03", "Pangolin lineage по consensus"),
    ("cs03", "ph01", "размещение на дереве с учётом lineage"),
    ("vc01", "ph02", "S-мутации идентифицируются из variant-calls"),
    ("ph01", "ph03", "кластеризация после размещения на дереве"),
]


# === scrnaseq === 16 узлов, 5 слоёв ===
SCRNASEQ_HYP = [
    {"id": "qc01", "layer": "QC",
     "text": "Q30 ≥ 30 на reads",
     "params": {"q_threshold": 30},
     "source": "Andrews 2010"},
    {"id": "qc02", "layer": "QC",
     "text": "доля reads с валидным cell-barcode ≥ 70%",
     "params": {"valid_barcode_rate": 0.70},
     "source": "Zheng 2017 (10x Genomics)"},
    {"id": "qc03", "layer": "QC",
     "text": "доля reads с валидным UMI ≥ 80%",
     "params": {"valid_umi_rate": 0.80},
     "source": "Zheng 2017"},
    {"id": "al01", "layer": "Alignment",
     "text": "≥ 60% reads картируются на транскриптом (STARsolo/Salmon)",
     "params": {"map_rate": 0.60, "tool": ["STARsolo", "alevin"]},
     "source": "Kaminow 2021 (STARsolo); Srivastava 2019 (alevin)"},
    {"id": "al02", "layer": "Alignment",
     "text": "saturation reads ≥ 60% (тренд rate ≈ 1)",
     "params": {"saturation_thr": 0.60},
     "source": "Zheng 2017"},
    {"id": "al03", "layer": "Alignment",
     "text": "доля intergenic reads < 25%",
     "params": {"intergenic_rate_thr": 0.25},
     "source": "Kaminow 2021"},
    {"id": "cm01", "layer": "CellMatrix",
     "text": "≥ 500 cells с ≥ 500 detected genes (EmptyDrops-фильтр)",
     "params": {"min_genes_per_cell": 500, "min_cells": 500,
                "tool": "EmptyDrops"},
     "source": "Lun 2019 (EmptyDrops)"},
    {"id": "cm02", "layer": "CellMatrix",
     "text": "доля mitochondrial UMI < 20% (для большинства клеток)",
     "params": {"mito_rate_thr": 0.20},
     "source": "Lun 2016 (scater)"},
    {"id": "cm03", "layer": "CellMatrix",
     "text": "doublet-rate < 10% (после Scrublet/DoubletFinder)",
     "params": {"doublet_thr": 0.10, "tool": ["Scrublet", "DoubletFinder"]},
     "source": "Wolock 2019 (Scrublet); McGinnis 2019 (DoubletFinder)"},
    {"id": "cl01", "layer": "Clustering",
     "text": "после нормализации (SCTransform/log-norm) HVG ≥ 2000",
     "params": {"min_hvg": 2000, "method": ["SCTransform", "log_norm"]},
     "source": "Hafemeister 2019 (SCTransform)"},
    {"id": "cl02", "layer": "Clustering",
     "text": "Leiden-кластеры стабильны (≥ 5 кластеров, modularity > 0.3)",
     "params": {"min_clusters": 5, "min_modularity": 0.30,
                "method": "leiden"},
     "source": "Traag 2019 (Leiden)"},
    {"id": "cl03", "layer": "Clustering",
     "text": "UMAP-эмбеддинг разделяет основные клеточные типы",
     "params": {"method": "umap", "min_neighbors": 15},
     "source": "McInnes 2018 (UMAP)"},
    {"id": "mk01", "layer": "Markers",
     "text": "∃ DE-маркеры на кластер (Wilcoxon, FDR<0.05, log2FC>0.5)",
     "params": {"test": "wilcoxon", "fdr": 0.05, "lfc_thr": 0.5},
     "source": "Stuart 2019 (Seurat v3)"},
    {"id": "mk02", "layer": "Markers",
     "text": "кластеры соответствуют known cell types (по cell-type-marker DB)",
     "params": {"db": ["CellMarker2", "PanglaoDB"]},
     "source": "Hu 2023 (CellMarker2); Franzén 2019 (PanglaoDB)"},
    {"id": "mk03", "layer": "Markers",
     "text": "транзиции между типами выявляются траектория-методом (Slingshot/PAGA)",
     "params": {"tool": ["Slingshot", "PAGA"]},
     "source": "Street 2018 (Slingshot); Wolf 2019 (PAGA)"},
    {"id": "mk04", "layer": "Markers",
     "text": "композиция кластеров различается между условиями (compositional analysis)",
     "params": {"test": ["scCODA", "milo"], "p_thr": 0.05},
     "source": "Büttner 2021 (scCODA); Dann 2022 (Milo)"},
]

SCRNASEQ_INTER_LAYER_EDGES = [
    ("qc01", "al01", "mapping требует качественных reads"),
    ("qc02", "al01", "barcodes — pre-condition для cell-assignment"),
    ("qc03", "al02", "saturation считается на UMI-deduplicated reads"),
    ("al01", "cm01", "cell-matrix строится из mapped reads + barcodes"),
    ("al02", "cm01", "saturation — индикатор глубины cell-matrix"),
    ("al03", "cm02", "mito-rate как QC-метрика клеток"),
    ("cm01", "cm03", "doublet-detection после фильтра empty droplets"),
    ("cm02", "cl01", "норма после mitochondrial фильтра"),
    ("cm03", "cl01", "норма после doublet-removal"),
    ("cl01", "cl02", "Leiden на PCA-graph HVG"),
    ("cl01", "cl03", "UMAP на тех же HVG-PCA"),
    ("cl02", "mk01", "DE-маркеры считаются на кластерах"),
    ("mk01", "mk02", "присвоение типов через маркеры"),
    ("cl02", "mk03", "траектория-anal по кластерам"),
    ("mk02", "mk03", "транзиции между known типами"),
    ("mk02", "mk04", "композиция типов между условиями"),
]


# === taxprofiler === 14 узлов, 5 слоёв ===
TAXPROFILER_HYP = [
    {"id": "qc01", "layer": "QC",
     "text": "Q30 ≥ 30 на метагеномных reads",
     "params": {"q_threshold": 30},
     "source": "Andrews 2010"},
    {"id": "qc02", "layer": "QC",
     "text": "длина reads после trim ≥ 50 bp у ≥ 80%",
     "params": {"min_length_bp": 50, "min_rate": 0.80},
     "source": "Martin 2011"},
    {"id": "qc03", "layer": "QC",
     "text": "complexity-фильтр исключил low-complexity reads (BBDuk)",
     "params": {"tool": "BBDuk", "complexity_filter": True},
     "source": "Bushnell 2014 (BBTools)"},
    {"id": "hf01", "layer": "HostFilter",
     "text": "host-removal оставляет < 5% host reads",
     "params": {"host_residual_thr": 0.05},
     "source": "Langmead 2012"},
    {"id": "hf02", "layer": "HostFilter",
     "text": "доля microbial reads после host-removal ≥ 90%",
     "params": {"microbial_rate_thr": 0.90},
     "source": "Lu 2022 (taxprofiler)"},
    {"id": "cl01", "layer": "Classification",
     "text": "Kraken2 классифицирует ≥ 60% microbial reads на уровне рода",
     "params": {"tool": "Kraken2", "min_classified_rate": 0.60, "level": "genus"},
     "source": "Wood 2019 (Kraken2)"},
    {"id": "cl02", "layer": "Classification",
     "text": "MetaPhlAn4 идентифицирует ≥ 50 species-level маркеров",
     "params": {"tool": "MetaPhlAn4", "min_species": 50},
     "source": "Blanco-Míguez 2023 (MetaPhlAn4)"},
    {"id": "cl03", "layer": "Classification",
     "text": "согласие классификаторов на топ-таксонах ≥ 70% (Jaccard)",
     "params": {"agreement_metric": "jaccard", "agreement_thr": 0.70},
     "source": "Lu 2022"},
    {"id": "ab01", "layer": "Abundance",
     "text": "relative abundance профиль нормирован к 1 на образец",
     "params": {"normalization": "TSS"},
     "source": "Lu 2022"},
    {"id": "ab02", "layer": "Abundance",
     "text": "Bracken-перекалибровка снижает overestimation для high-rank taxa",
     "params": {"tool": "Bracken"},
     "source": "Lu 2017 (Bracken)"},
    {"id": "ab03", "layer": "Abundance",
     "text": "abundance-профиль воспроизводится между техническими replicates (rho≥0.95)",
     "params": {"correlation": "spearman", "thr": 0.95, "scope": "replicate"},
     "source": "Lu 2022"},
    {"id": "cp01", "layer": "Comparative",
     "text": "α-разнообразие различается между группами (Wilcoxon, p<0.05)",
     "params": {"test": "wilcoxon", "p_thr": 0.05, "scope": "alpha"},
     "source": "Magurran 2004"},
    {"id": "cp02", "layer": "Comparative",
     "text": "β-разнообразие отделяет группы (PERMANOVA, p<0.05)",
     "params": {"test": "PERMANOVA", "p_thr": 0.05, "scope": "beta"},
     "source": "Anderson 2001"},
    {"id": "cp03", "layer": "Comparative",
     "text": "∃ дифференциально представленные таксоны (LEfSe, LDA>2)",
     "params": {"tool": "LEfSe", "lda_thr": 2.0},
     "source": "Segata 2011 (LEfSe)"},
]

TAXPROFILER_INTER_LAYER_EDGES = [
    ("qc01", "hf01", "host-mapping требует качественных reads"),
    ("qc02", "cl01", "длина — pre-condition для k-mer классификации"),
    ("qc03", "cl01", "low-complexity искажает k-mer counts"),
    ("hf01", "hf02", "microbial rate — комплемент к host"),
    ("hf02", "cl01", "Kraken2 на microbial reads"),
    ("hf02", "cl02", "MetaPhlAn4 на microbial reads"),
    ("cl01", "cl03", "agreement рассчитан между классификаторами"),
    ("cl02", "cl03", "agreement рассчитан между классификаторами"),
    ("cl01", "ab01", "abundance из classification"),
    ("cl02", "ab01", "abundance из marker-based профиля"),
    ("ab01", "ab02", "Bracken-перекалибровка работает на k-mer abundance"),
    ("ab01", "ab03", "технические replicates сравнивают одинаковые abundance"),
    ("ab02", "cp01", "сравнения после перекалибровки"),
    ("ab02", "cp02", "сравнения после перекалибровки"),
    ("cp01", "cp03", "LEfSe строится на разнообразии-кандидатах"),
    ("cp02", "cp03", "differential taxa координированы с group-разделением"),
]


# === eager === 15 узлов, 5 слоёв (ancient DNA) ===
EAGER_HYP = [
    {"id": "qc01", "layer": "QC",
     "text": "Q30 ≥ 30 на короткие aDNA reads",
     "params": {"q_threshold": 30},
     "source": "Andrews 2010"},
    {"id": "qc02", "layer": "QC",
     "text": "распределение длин: преобладание fragments ≤ 100 bp",
     "params": {"max_length_bp": 100, "scope": "majority"},
     "source": "Briggs 2007 (aDNA fragmentation)"},
    {"id": "qc03", "layer": "QC",
     "text": "adapter-trimming успешен ≥ 95%",
     "params": {"trim_rate": 0.95},
     "source": "Schubert 2014 (AdapterRemoval)"},
    {"id": "al01", "layer": "Alignment",
     "text": "≥ 30% reads картируются BWA aln на референс",
     "params": {"map_rate": 0.30, "aligner": "bwa_aln"},
     "source": "Schubert 2012 (BWA aln aDNA)"},
    {"id": "al02", "layer": "Alignment",
     "text": "≥ 95% mapped reads имеют MAPQ ≥ 25",
     "params": {"mapq_thr": 25, "min_rate": 0.95},
     "source": "Schubert 2012"},
    {"id": "al03", "layer": "Alignment",
     "text": "среднее покрытие генома ≥ 1× (низкое покрытие aDNA)",
     "params": {"min_coverage": 1.0},
     "source": "Slatkin 2016 (aDNA review)"},
    {"id": "dm01", "layer": "DamageCorrection",
     "text": "C-to-T misincorporation rate ≥ 5% в первых 5 bp 5'-конца",
     "params": {"misincorp_min": 0.05, "scope": "5p_first_5bp"},
     "source": "Jónsson 2013 (mapDamage); Briggs 2007"},
    {"id": "dm02", "layer": "DamageCorrection",
     "text": "повышенная G-to-A misincorp на 3'-конце (single-strand library)",
     "params": {"misincorp_min": 0.05, "scope": "3p_first_5bp",
                "library_type": "single_strand"},
     "source": "Gansauge 2013"},
    {"id": "dm03", "layer": "DamageCorrection",
     "text": "после rescaling качества damage-patterns сглажены",
     "params": {"tool": "mapDamage2_rescale"},
     "source": "Jónsson 2013"},
    {"id": "va01", "layer": "Variant",
     "text": "∃ SNV-варианты на pseudohaploid-genotypes (GATK/ANGSD)",
     "params": {"tool": ["GATK", "ANGSD"], "method": "pseudohaploid"},
     "source": "Korneliussen 2014 (ANGSD)"},
    {"id": "va02", "layer": "Variant",
     "text": "вариант-набор отображается на reference-панель (1000G/HO)",
     "params": {"reference_panel": ["1000G", "HO"]},
     "source": "Patterson 2012"},
    {"id": "va03", "layer": "Variant",
     "text": "доля Ti/Tv ∈ [1.9, 2.2]",
     "params": {"ti_tv_range": [1.9, 2.2]},
     "source": "Wang 2015"},
    {"id": "au01", "layer": "Authentication",
     "text": "MapDamage подтверждает aDNA-сигнатуру (damage>5%)",
     "params": {"min_damage_rate": 0.05},
     "source": "Jónsson 2013"},
    {"id": "au02", "layer": "Authentication",
     "text": "contamination-estimation < 5% (Schmutzi/ANGSD-X)",
     "params": {"contam_thr": 0.05, "tool": ["Schmutzi", "ANGSD-X"]},
     "source": "Renaud 2015 (Schmutzi)"},
    {"id": "au03", "layer": "Authentication",
     "text": "результаты PCA согласуются с временным/географическим контекстом",
     "params": {"method": "pca", "metadata": ["time", "geo"]},
     "source": "Patterson 2012"},
]

EAGER_INTER_LAYER_EDGES = [
    ("qc01", "al01", "mapping требует качественных reads"),
    ("qc02", "al01", "короткие aDNA-fragments — особенность mapping"),
    ("qc03", "al01", "adapter-trim — pre-condition"),
    ("al01", "al02", "MAPQ-фильтр на mapped reads"),
    ("al02", "al03", "coverage на качественно mapped reads"),
    ("al02", "dm01", "damage-detection на mapped reads"),
    ("al02", "dm02", "G-to-A на mapped reads"),
    ("dm01", "dm03", "rescaling — после оценки damage"),
    ("dm02", "dm03", "rescaling также по 3'-damage"),
    ("dm03", "va01", "variant calling на rescaled reads"),
    ("va01", "va02", "panel-отображение по called SNV"),
    ("va01", "va03", "Ti/Tv статистика variant-set"),
    ("dm01", "au01", "MapDamage-сигнатура как authentication"),
    ("al02", "au02", "contam-estimation требует качественных mapped reads"),
    ("va02", "au03", "PCA по panel-projected genotypes"),
    ("au01", "au03", "authentication совмещается с PCA-контекстом"),
]


# === cutandrun === 14 узлов, 5 слоёв ===
CUTANDRUN_HYP = [
    {"id": "qc01", "layer": "QC",
     "text": "Q30 ≥ 30 на CUT&RUN reads",
     "params": {"q_threshold": 30},
     "source": "Andrews 2010"},
    {"id": "qc02", "layer": "QC",
     "text": "доля duplicate-reads < 25%",
     "params": {"duplicate_thr": 0.25},
     "source": "Skene 2017 (CUT&RUN)"},
    {"id": "qc03", "layer": "QC",
     "text": "fragment-size distribution имеет mononucleosomal peak ~120-180 bp",
     "params": {"fragment_peak_bp": [120, 180]},
     "source": "Skene 2017"},
    {"id": "al01", "layer": "Alignment",
     "text": "≥ 70% reads картируются Bowtie2/BWA",
     "params": {"map_rate": 0.70, "aligner": ["bowtie2", "bwa"]},
     "source": "Langmead 2012 (Bowtie2)"},
    {"id": "al02", "layer": "Alignment",
     "text": "spike-in нормировка (E. coli) — calibration factor применён",
     "params": {"spike_in": "E_coli", "normalization": "calibration_factor"},
     "source": "Meers 2019 (CUT&RUN spike-in)"},
    {"id": "pk01", "layer": "PeakCalling",
     "text": "∃ SEACR-peaks (stringent threshold)",
     "params": {"caller": "SEACR", "mode": "stringent"},
     "source": "Meers 2019 (SEACR)"},
    {"id": "pk02", "layer": "PeakCalling",
     "text": "FRiP ≥ 0.20 (CUT&RUN типично)",
     "params": {"frip_thr": 0.20},
     "source": "Meers 2019"},
    {"id": "pk03", "layer": "PeakCalling",
     "text": "consensus peak-set между replicates ≥ 60% overlap",
     "params": {"replicate_overlap_thr": 0.60},
     "source": "Skene 2017"},
    {"id": "db01", "layer": "DiffBinding",
     "text": "∃ differentially bound peaks (DiffBind, FDR<0.05)",
     "params": {"fdr": 0.05, "tool": "DiffBind"},
     "source": "Ross-Innes 2012"},
    {"id": "db02", "layer": "DiffBinding",
     "text": "∃ gain-of-binding peaks (log2FC > 1)",
     "params": {"fdr": 0.05, "tool": "DiffBind", "lfc_thr": 1.0,
                "direction": "gain"},
     "source": "subsumption(db01)"},
    {"id": "db03", "layer": "DiffBinding",
     "text": "∃ loss-of-binding peaks (log2FC < -1)",
     "params": {"fdr": 0.05, "tool": "DiffBind", "lfc_thr": 1.0,
                "direction": "loss"},
     "source": "subsumption(db01)"},
    {"id": "mt01", "layer": "Motif",
     "text": "∃ обогащённые TF-мотивы (MEME-ChIP, p<1e-5)",
     "params": {"tool": "MEME-ChIP", "p_thr": 1e-5},
     "source": "Bailey 2011"},
    {"id": "mt02", "layer": "Motif",
     "text": "обогащённый мотив соответствует канонической PWM из JASPAR",
     "params": {"db": "JASPAR"},
     "source": "Castro-Mondragon 2022"},
    {"id": "mt03", "layer": "Motif",
     "text": "DB-peaks ассоциируются с регуляторными элементами",
     "params": {"annotation": "ChromHMM"},
     "source": "Ernst 2011"},
]

CUTANDRUN_INTER_LAYER_EDGES = [
    ("qc01", "al01", "mapping требует качественных reads"),
    ("qc02", "al01", "duplicate-фильтр — pre-condition для нормировки"),
    ("qc03", "pk01", "mononucleosomal fragments — основа CUT&RUN-сигнала"),
    ("al01", "al02", "spike-in нормировка после mapping"),
    ("al02", "pk01", "calibrated reads — вход для SEACR"),
    ("pk01", "pk02", "FRiP на peak-set"),
    ("pk01", "pk03", "consensus через peak-sets replicates"),
    ("pk03", "db01", "DiffBind на consensus"),
    ("db01", "db02", "gain — подмножество DB"),
    ("db01", "db03", "loss — подмножество DB"),
    ("db01", "mt01", "motif-обогащение на DB"),
    ("mt01", "mt02", "PWM-валидация мотивов"),
    ("db01", "mt03", "регуляторная аннотация на DB"),
    ("db02", "mt03", "регуляторная аннотация на gain"),
]


# === smrnaseq === 14 узлов, 5 слоёв ===
SMRNASEQ_HYP = [
    {"id": "qc01", "layer": "QC",
     "text": "Q30 ≥ 30 на small-RNA reads",
     "params": {"q_threshold": 30},
     "source": "Andrews 2010"},
    {"id": "qc02", "layer": "QC",
     "text": "длина reads после trim 18-30 bp — преобладает (≥80%)",
     "params": {"length_range_bp": [18, 30], "min_rate": 0.80},
     "source": "Friedländer 2012 (miRDeep2)"},
    {"id": "qc03", "layer": "QC",
     "text": "adapter-trimming успешен ≥ 90% reads",
     "params": {"trim_rate": 0.90},
     "source": "Martin 2011"},
    {"id": "fl01", "layer": "Filtering",
     "text": "ribo/tRNA/rRNA-reads отфильтрованы (< 30% после)",
     "params": {"max_rrna_rate_after_filter": 0.30},
     "source": "Friedländer 2012"},
    {"id": "fl02", "layer": "Filtering",
     "text": "доля reads, пригодных для miRNA-quantification ≥ 30%",
     "params": {"min_mirna_compatible_rate": 0.30},
     "source": "Friedländer 2012"},
    {"id": "mq01", "layer": "miRNAQuant",
     "text": "≥ 100 известных miRNA с counts > 10 (miRBase)",
     "params": {"min_known_mirnas": 100, "min_counts": 10,
                "db": "miRBase"},
     "source": "Kozomara 2019 (miRBase)"},
    {"id": "mq02", "layer": "miRNAQuant",
     "text": "идентифицированы кандидаты в novel miRNA (miRDeep2 score > 5)",
     "params": {"tool": "miRDeep2", "min_score": 5.0},
     "source": "Friedländer 2012"},
    {"id": "mq03", "layer": "miRNAQuant",
     "text": "распределение miRNA-counts следует heavy-tail",
     "params": {"distribution": "heavy_tail"},
     "source": "Friedländer 2012"},
    {"id": "de01", "layer": "DE",
     "text": "∃ DE-miRNA между группами (DESeq2, FDR<0.05)",
     "params": {"fdr": 0.05, "tool": "DESeq2"},
     "source": "Love 2014"},
    {"id": "de02", "layer": "DE",
     "text": "∃ up-DE-miRNA (log2FC > 1)",
     "params": {"fdr": 0.05, "lfc_thr": 1.0, "direction": "up"},
     "source": "subsumption(de01)"},
    {"id": "de03", "layer": "DE",
     "text": "∃ down-DE-miRNA (log2FC < -1)",
     "params": {"fdr": 0.05, "lfc_thr": 1.0, "direction": "down"},
     "source": "subsumption(de01)"},
    {"id": "tp01", "layer": "TargetPred",
     "text": "DE-miRNA имеют предсказанные мишени (TargetScan/miRDB)",
     "params": {"tool": ["TargetScan", "miRDB"]},
     "source": "Agarwal 2015 (TargetScan); Chen 2020 (miRDB)"},
    {"id": "tp02", "layer": "TargetPred",
     "text": "мишени up-DE-miRNA антикоррелируют с mRNA-DE (если есть пара)",
     "params": {"correlation": "spearman", "expected_sign": "negative"},
     "source": "Stark 2003"},
    {"id": "tp03", "layer": "TargetPred",
     "text": "функциональные пути мишеней обогащены (Fisher, FDR<0.05)",
     "params": {"test": "fisher", "fdr": 0.05},
     "source": "Kanehisa 2017"},
]

SMRNASEQ_INTER_LAYER_EDGES = [
    ("qc01", "fl01", "filtering требует качественных reads"),
    ("qc02", "fl02", "длина — селектор miRNA-кандидатов"),
    ("qc03", "fl01", "trim — pre-condition фильтра"),
    ("fl01", "fl02", "miRNA-pool после ribo/tRNA-удаления"),
    ("fl02", "mq01", "quantification на miRNA-compatible reads"),
    ("mq01", "mq02", "novel-обнаружение использует тот же mapping"),
    ("mq01", "mq03", "распределение — статистика counts"),
    ("mq01", "de01", "DESeq2 на counts известных miRNA"),
    ("de01", "de02", "up — subset DE"),
    ("de01", "de03", "down — subset DE"),
    ("de01", "tp01", "target-prediction для DE-miRNA"),
    ("de02", "tp02", "антикорреляция specifically для up-miRNA"),
    ("tp01", "tp03", "pathway-enrichment по target-генам"),
    ("tp02", "tp03", "корректная антикорреляция усиливает pathway-интерпретацию"),
]


# === dualrnaseq === 15 узлов, 5 слоёв (host-pathogen) ===
DUALRNASEQ_HYP = [
    {"id": "qc01", "layer": "QC",
     "text": "Q30 ≥ 30 на dual host+pathogen reads",
     "params": {"q_threshold": 30},
     "source": "Westermann 2017 (dual RNA-seq)"},
    {"id": "qc02", "layer": "QC",
     "text": "доля reads после trim ≥ 90%",
     "params": {"trim_rate": 0.90},
     "source": "Martin 2011"},
    {"id": "qc03", "layer": "QC",
     "text": "доля адаптерной контаминации < 5%",
     "params": {"contamination_thr": 0.05},
     "source": "Martin 2011"},
    {"id": "sa01", "layer": "SplitAlign",
     "text": "≥ 70% reads картируются на объединённый host+pathogen-индекс",
     "params": {"map_rate": 0.70, "scope": "joint_index"},
     "source": "Westermann 2017"},
    {"id": "sa02", "layer": "SplitAlign",
     "text": "доля host-reads ≥ 80% (типично для in vitro infection)",
     "params": {"host_rate_thr": 0.80, "context": "infection_invitro"},
     "source": "Westermann 2017"},
    {"id": "sa03", "layer": "SplitAlign",
     "text": "доля pathogen-reads ≥ 1% (для детекции)",
     "params": {"pathogen_rate_thr": 0.01},
     "source": "Westermann 2017"},
    {"id": "ct01", "layer": "Counting",
     "text": "≥ 50% host-генов имеют counts > 1",
     "params": {"gene_coverage": 0.50, "scope": "host"},
     "source": "Liao 2014"},
    {"id": "ct02", "layer": "Counting",
     "text": "≥ 30% pathogen-генов имеют counts > 1 (sparser)",
     "params": {"gene_coverage": 0.30, "scope": "pathogen"},
     "source": "Westermann 2017"},
    {"id": "ct03", "layer": "Counting",
     "text": "rRNA-доля pathogen-counts < 50% (rRNA-зависит от подготовки)",
     "params": {"rrna_rate_thr": 0.50},
     "source": "Westermann 2017"},
    {"id": "de01", "layer": "DE",
     "text": "∃ DE-host-гены между инфицированными и контролем (FDR<0.05)",
     "params": {"fdr": 0.05, "scope": "host", "tool": "DESeq2"},
     "source": "Love 2014"},
    {"id": "de02", "layer": "DE",
     "text": "∃ DE-pathogen-гены между condition A и B (FDR<0.05)",
     "params": {"fdr": 0.05, "scope": "pathogen", "tool": "DESeq2"},
     "source": "Love 2014"},
    {"id": "de03", "layer": "DE",
     "text": "иммунные сигнатуры (GO immune response) обогащены среди up-host-DE",
     "params": {"set": "GO", "category": "immune_response", "test": "fisher"},
     "source": "Westermann 2017"},
    {"id": "ct01x", "layer": "Crosstalk",
     "text": "host- и pathogen-DE коррелируют в~подгруппах образцов",
     "params": {"correlation": "spearman", "p_thr": 0.05},
     "source": "Westermann 2017"},
    {"id": "ct02x", "layer": "Crosstalk",
     "text": "host-pathway-pathogen-effector пары идентифицированы (literature/STRING)",
     "params": {"sources": ["literature", "STRING"]},
     "source": "Szklarczyk 2019"},
    {"id": "ct03x", "layer": "Crosstalk",
     "text": "time-series даёт временной паттерн host vs pathogen-DE",
     "params": {"design": "time_series"},
     "source": "Westermann 2017"},
]

DUALRNASEQ_INTER_LAYER_EDGES = [
    ("qc01", "sa01", "split-alignment требует качественных reads"),
    ("qc02", "sa01", "trim — pre-condition"),
    ("qc03", "sa01", "адаптеры искажают split-mapping"),
    ("sa01", "sa02", "host-rate из split-mapping"),
    ("sa01", "sa03", "pathogen-rate из split-mapping"),
    ("sa02", "ct01", "host-counting на host-reads"),
    ("sa03", "ct02", "pathogen-counting на pathogen-reads"),
    ("sa03", "ct03", "rRNA-доля среди pathogen-counts"),
    ("ct01", "de01", "DE-host на host-counts"),
    ("ct02", "de02", "DE-pathogen на pathogen-counts"),
    ("de01", "de03", "иммунное обогащение по host-DE"),
    ("de01", "ct01x", "корреляция host-pathogen-DE"),
    ("de02", "ct01x", "корреляция host-pathogen-DE"),
    ("ct01x", "ct02x", "идентификация специфичных пар"),
    ("de01", "ct03x", "host-DE как точка временного паттерна"),
    ("de02", "ct03x", "pathogen-DE как точка временного паттерна"),
]


# === bacass === 14 узлов, 5 слоёв (bacterial assembly) ===
BACASS_HYP = [
    {"id": "qc01", "layer": "QC",
     "text": "Q30 ≥ 30 на reads",
     "params": {"q_threshold": 30},
     "source": "Andrews 2010"},
    {"id": "qc02", "layer": "QC",
     "text": "доля adapter-контаминации < 5%",
     "params": {"contamination_thr": 0.05},
     "source": "Martin 2011"},
    {"id": "qc03", "layer": "QC",
     "text": "среднее покрытие ≥ 30× (short-read) или ≥ 20× (long-read)",
     "params": {"min_coverage_short": 30, "min_coverage_long": 20},
     "source": "Wick 2017 (Unicycler)"},
    {"id": "as01", "layer": "Assembly",
     "text": "Unicycler/SPAdes даёт сборку с N50 ≥ 50 kb",
     "params": {"assembler": ["Unicycler", "SPAdes"], "n50_min_bp": 50000},
     "source": "Wick 2017"},
    {"id": "as02", "layer": "Assembly",
     "text": "число contigs ≤ 100 для типичного бактериального генома",
     "params": {"max_contigs": 100},
     "source": "Bankevich 2012 (SPAdes)"},
    {"id": "as03", "layer": "Assembly",
     "text": "общая длина сборки соответствует ожидаемому размеру генома (±10%)",
     "params": {"size_tolerance_pct": 10},
     "source": "Wick 2017"},
    {"id": "pl01", "layer": "Polish",
     "text": "Polypolish/Pilon-полировка исправляет ≥ 95% k-mer-разногласий",
     "params": {"tool": ["Polypolish", "Pilon"], "kmer_fix_rate": 0.95},
     "source": "Wick 2022 (Polypolish); Walker 2014 (Pilon)"},
    {"id": "pl02", "layer": "Polish",
     "text": "после полировки nucleotide-identity к референсу ≥ 99,9%",
     "params": {"ident_thr": 0.999},
     "source": "Wick 2022"},
    {"id": "an01", "layer": "Annotation",
     "text": "Prokka/Bakta аннотируют ≥ 95% CDS",
     "params": {"tool": ["Prokka", "Bakta"], "min_cds_rate": 0.95},
     "source": "Seemann 2014 (Prokka); Schwengers 2021 (Bakta)"},
    {"id": "an02", "layer": "Annotation",
     "text": "∃ известные resistance-гены (CARD/AMRFinder)",
     "params": {"db": ["CARD", "AMRFinder"]},
     "source": "Alcock 2020; Feldgarden 2021"},
    {"id": "an03", "layer": "Annotation",
     "text": "∃ vifrulence-факторы (VFDB)",
     "params": {"db": "VFDB"},
     "source": "Liu 2022 (VFDB)"},
    {"id": "cm01", "layer": "Comparative",
     "text": "штамм классифицирован MLST",
     "params": {"tool": "MLST"},
     "source": "Maiden 1998"},
    {"id": "cm02", "layer": "Comparative",
     "text": "ANI к референсу ≥ 95% (определение вида)",
     "params": {"ani_thr": 0.95},
     "source": "Goris 2007 (ANI)"},
    {"id": "cm03", "layer": "Comparative",
     "text": "филогенетическое положение согласовано с метаданной",
     "params": {"method": "core_genome_tree"},
     "source": "Wick 2017"},
]

BACASS_INTER_LAYER_EDGES = [
    ("qc01", "as01", "assembly требует качественных reads"),
    ("qc02", "as01", "адаптеры искажают сборку"),
    ("qc03", "as01", "достаточное покрытие — pre-condition"),
    ("as01", "as02", "contig-count — статистика сборки"),
    ("as01", "as03", "общая длина — статистика сборки"),
    ("as01", "pl01", "polishing на сборку"),
    ("pl01", "pl02", "identity после полировки"),
    ("pl02", "an01", "аннотация на отполированной сборке"),
    ("an01", "an02", "AMR-поиск среди аннотированных"),
    ("an01", "an03", "virulence-поиск среди аннотированных"),
    ("an01", "cm01", "MLST на CDS"),
    ("pl02", "cm02", "ANI к референсу"),
    ("cm01", "cm03", "phylogenetic placement по MLST/core-genome"),
    ("cm02", "cm03", "ANI поддерживает видовое размещение"),
]


# === nanoseq === 14 узлов, 5 слоёв (Oxford Nanopore) ===
NANOSEQ_HYP = [
    {"id": "bc01", "layer": "Basecall",
     "text": "Guppy/Dorado даёт mean-Q ≥ 10 на large fraction reads",
     "params": {"tool": ["Guppy", "Dorado"], "min_mean_q": 10},
     "source": "Wick 2019 (Guppy benchmarks)"},
    {"id": "bc02", "layer": "Basecall",
     "text": "≥ 80% reads classified как pass-quality",
     "params": {"pass_rate": 0.80},
     "source": "Wick 2019"},
    {"id": "bc03", "layer": "Basecall",
     "text": "N50 длины reads ≥ 10 kb (для типичных library)",
     "params": {"n50_min_bp": 10000},
     "source": "Jain 2018 (nanopore review)"},
    {"id": "qc01", "layer": "QC",
     "text": "доля коротких reads (<200 bp) < 20%",
     "params": {"short_read_thr_bp": 200, "max_rate": 0.20},
     "source": "Jain 2018"},
    {"id": "qc02", "layer": "QC",
     "text": "median per-read accuracy ≥ 90%",
     "params": {"min_accuracy": 0.90},
     "source": "Wick 2019"},
    {"id": "al01", "layer": "Alignment",
     "text": "≥ 90% pass-reads картируются Minimap2",
     "params": {"map_rate": 0.90, "aligner": "minimap2"},
     "source": "Li 2018 (Minimap2)"},
    {"id": "al02", "layer": "Alignment",
     "text": "среднее покрытие ≥ 20×",
     "params": {"min_coverage": 20},
     "source": "Jain 2018"},
    {"id": "al03", "layer": "Alignment",
     "text": "доля split-reads / chimeric < 10%",
     "params": {"chimeric_rate_thr": 0.10},
     "source": "Li 2018"},
    {"id": "sv01", "layer": "SVMeth",
     "text": "∃ structural variants (Sniffles, support ≥ 5)",
     "params": {"tool": "Sniffles", "min_support": 5},
     "source": "Sedlazeck 2018 (Sniffles)"},
    {"id": "sv02", "layer": "SVMeth",
     "text": "обнаружены methylation calls (5mC/6mA) через Nanopolish/Remora",
     "params": {"tool": ["Nanopolish", "Remora"], "modifications": ["5mC", "6mA"]},
     "source": "Simpson 2017 (Nanopolish)"},
    {"id": "sv03", "layer": "SVMeth",
     "text": "valid SV-сet консистентен между repeats",
     "params": {"consistency_thr": 0.80},
     "source": "Sedlazeck 2018"},
    {"id": "vr01", "layer": "Variant",
     "text": "∃ SNV/indels (Clair3 или PEPPER-DeepVariant)",
     "params": {"tool": ["Clair3", "PEPPER-DeepVariant"]},
     "source": "Zheng 2022 (Clair3); Shafin 2021 (PEPPER)"},
    {"id": "vr02", "layer": "Variant",
     "text": "Ti/Tv ∈ [2.0, 2.2] для germline",
     "params": {"ti_tv_range": [2.0, 2.2]},
     "source": "Wang 2015"},
    {"id": "vr03", "layer": "Variant",
     "text": "phasing (WhatsHap) даёт haplotype-blocks ≥ 100 kb",
     "params": {"tool": "WhatsHap", "min_block_kb": 100},
     "source": "Patterson 2015 (WhatsHap)"},
]

NANOSEQ_INTER_LAYER_EDGES = [
    ("bc01", "qc01", "длина post-basecall"),
    ("bc02", "qc02", "accuracy на pass-reads"),
    ("bc03", "qc01", "N50 коррелирует с долей коротких"),
    ("qc01", "al01", "mapping требует не-слишком-коротких"),
    ("qc02", "al01", "accuracy — pre-condition mapping"),
    ("al01", "al02", "coverage на mapped"),
    ("al01", "al03", "chimeric-rate на mapped"),
    ("al02", "sv01", "SV-вызов требует покрытия"),
    ("al02", "sv02", "методилирование требует покрытия"),
    ("sv01", "sv03", "консистентность SV-set"),
    ("al02", "vr01", "SNV-вызов на покрытии"),
    ("vr01", "vr02", "Ti/Tv статистика SNV-set"),
    ("vr01", "vr03", "phasing на called variants"),
    ("sv01", "vr03", "phasing использует SV-context"),
]


# === demultiplex === 13 узлов, 5 слоёв ===
DEMULTIPLEX_HYP = [
    {"id": "ss01", "layer": "SampleSheet",
     "text": "samplesheet содержит уникальные barcode-пары для всех образцов",
     "params": {"unique_barcodes": True},
     "source": "Illumina BCL specification"},
    {"id": "ss02", "layer": "SampleSheet",
     "text": "barcode-расстояния ≥ Hamming-distance 3",
     "params": {"min_hamming_distance": 3},
     "source": "Costello 2018 (index design)"},
    {"id": "ss03", "layer": "SampleSheet",
     "text": "samplesheet-validation проходит (формат, обязательные поля)",
     "params": {"validator": "samplesheet_validator"},
     "source": "nf-core/demultiplex docs"},
    {"id": "dx01", "layer": "Demux",
     "text": "BCL-Convert/bcl2fastq успешно демультиплексирует runs",
     "params": {"tool": ["BCL-Convert", "bcl2fastq"]},
     "source": "Illumina BCL-Convert manual"},
    {"id": "dx02", "layer": "Demux",
     "text": "≥ 90% reads назначены образцу",
     "params": {"assigned_rate": 0.90},
     "source": "Illumina"},
    {"id": "dx03", "layer": "Demux",
     "text": "undetermined-reads анализированы (top-N не-назначенных barcode)",
     "params": {"top_n_undetermined": 20},
     "source": "Costello 2018"},
    {"id": "qc01", "layer": "QC",
     "text": "Q30 ≥ 75% bases на образец",
     "params": {"q30_rate_thr": 0.75},
     "source": "Illumina QC"},
    {"id": "qc02", "layer": "QC",
     "text": "cluster density в expected range",
     "params": {"density_target": "in_range"},
     "source": "Illumina"},
    {"id": "qc03", "layer": "QC",
     "text": "образцы не пересекаются (lane bleeding < 1%)",
     "params": {"max_bleeding_rate": 0.01},
     "source": "Costello 2018"},
    {"id": "tr01", "layer": "Trim",
     "text": "адаптеры обрезаны (Trim Galore/fastp) с rate ≥ 95%",
     "params": {"trim_rate": 0.95, "tool": ["TrimGalore", "fastp"]},
     "source": "Krueger 2012 (Trim Galore); Chen 2018 (fastp)"},
    {"id": "tr02", "layer": "Trim",
     "text": "длина reads после trim ≥ 50 bp для ≥ 80%",
     "params": {"min_length_bp": 50, "min_rate": 0.80},
     "source": "Chen 2018"},
    {"id": "ou01", "layer": "Output",
     "text": "FASTQ-files валидны (FQC pass)",
     "params": {"validator": "fastqc_pass"},
     "source": "Andrews 2010"},
    {"id": "ou02", "layer": "Output",
     "text": "MultiQC-report содержит все метрики (basecall, demux, QC, trim)",
     "params": {"report_tool": "MultiQC"},
     "source": "Ewels 2016 (MultiQC)"},
]

DEMULTIPLEX_INTER_LAYER_EDGES = [
    ("ss01", "dx01", "uniq barcodes — pre-condition демультиплексирования"),
    ("ss02", "dx01", "достаточные расстояния минимизируют misassignment"),
    ("ss03", "dx01", "валидный samplesheet — pre-condition"),
    ("dx01", "dx02", "assigned-rate из результата демультиплексирования"),
    ("dx01", "dx03", "undetermined анализируются после демультиплексирования"),
    ("dx02", "qc01", "Q30 на assigned reads"),
    ("dx02", "qc03", "lane bleeding оценивается через assigned"),
    ("dx02", "tr01", "trim на демультиплексированных reads"),
    ("tr01", "tr02", "длина после trim"),
    ("tr02", "ou01", "FASTQ-валидация после trim"),
    ("ou01", "ou02", "MultiQC агрегирует все метрики"),
    ("qc01", "ou02", "QC-метрики попадают в отчёт"),
    ("dx02", "ou02", "demux-метрики попадают в отчёт"),
    ("tr01", "ou02", "trim-метрики попадают в отчёт"),
]


# === hgtseq === 13 узлов, 5 слоёв (horizontal gene transfer) ===
HGTSEQ_HYP = [
    {"id": "qc01", "layer": "QC",
     "text": "Q30 ≥ 30 на reads образца с потенциальным HGT",
     "params": {"q_threshold": 30},
     "source": "Andrews 2010"},
    {"id": "qc02", "layer": "QC",
     "text": "адаптерная контаминация < 5%",
     "params": {"contamination_thr": 0.05},
     "source": "Martin 2011"},
    {"id": "qc03", "layer": "QC",
     "text": "среднее покрытие ≥ 30×",
     "params": {"min_coverage": 30},
     "source": "nf-core/hgtseq docs"},
    {"id": "al01", "layer": "Alignment",
     "text": "≥ 90% reads картируются на host-референс",
     "params": {"map_rate_host": 0.90},
     "source": "Li 2013"},
    {"id": "al02", "layer": "Alignment",
     "text": "извлечён set неотображённых/частично-отображённых reads",
     "params": {"flag": "unmapped_or_partial"},
     "source": "nf-core/hgtseq docs"},
    {"id": "al03", "layer": "Alignment",
     "text": "split-read pairs идентифицированы (host-anchored)",
     "params": {"read_class": "split_pair"},
     "source": "Robinson 2017"},
    {"id": "cr01", "layer": "ChimericReads",
     "text": "≥ 100 кандидатных chimeric reads на образец",
     "params": {"min_chimeric_reads": 100},
     "source": "Robinson 2017"},
    {"id": "cr02", "layer": "ChimericReads",
     "text": "≥ 50% chimeric reads классифицируются Kraken2 как microbial",
     "params": {"min_microbial_rate": 0.50, "tool": "Kraken2"},
     "source": "Wood 2019"},
    {"id": "cr03", "layer": "ChimericReads",
     "text": "доля low-complexity chimeric < 30% (после complexity-фильтра)",
     "params": {"max_low_complexity_rate": 0.30},
     "source": "Bushnell 2014"},
    {"id": "he01", "layer": "HGTEvents",
     "text": "∃ candidate HGT events ≥ 5 supporting reads",
     "params": {"min_support_reads": 5},
     "source": "Robinson 2017"},
    {"id": "he02", "layer": "HGTEvents",
     "text": "HGT events воспроизводятся в independent replicates",
     "params": {"replicate_consistency_thr": 0.50},
     "source": "Robinson 2017"},
    {"id": "an01", "layer": "Annotation",
     "text": "HGT-локусы аннотированы (gene, biotype через VEP/Ensembl)",
     "params": {"annotator": "VEP", "db": "ENSEMBL"},
     "source": "McLaren 2016"},
    {"id": "an02", "layer": "Annotation",
     "text": "microbial-origin таксон идентифицирован (BLAST/Kraken2)",
     "params": {"tools": ["BLAST", "Kraken2"]},
     "source": "Altschul 1990 (BLAST)"},
]

HGTSEQ_INTER_LAYER_EDGES = [
    ("qc01", "al01", "alignment требует качественных reads"),
    ("qc02", "al01", "адаптеры искажают mapping"),
    ("qc03", "al02", "извлечение non-host требует достаточного покрытия"),
    ("al01", "al02", "non-host подмножество от mapping"),
    ("al02", "al03", "split-pairs — категория частично-отображённых"),
    ("al03", "cr01", "chimeric-кандидаты из split-pair set"),
    ("cr01", "cr02", "классификация на chimeric-set"),
    ("cr01", "cr03", "complexity-фильтр на тех же reads"),
    ("cr02", "he01", "HGT-events требуют microbial-classified chimeric"),
    ("cr03", "he01", "low-complexity не считается за supporting reads"),
    ("he01", "he02", "replicates-консистентность по событиям"),
    ("he02", "an01", "VEP-аннотация на устойчивых событиях"),
    ("cr02", "an02", "источник microbial-origin таксон"),
    ("an01", "an02", "аннотация локуса и origin-таксона связаны"),
]


def subsumption_edges(hyp_list: list[dict]) -> list[tuple]:
    """Hyppo-упрощённая subsumption: внутри одного слоя ребро ставится,
    если params(src) — собственное подмножество params(tgt) (по парам
    ключ=значение). Это передаёт «общая → специализированная»
    зависимость в~духе [kovalev2019constructing]."""
    edges = []
    by_layer = {}
    for h in hyp_list:
        by_layer.setdefault(h["layer"], []).append(h)
    for layer, hs in by_layer.items():
        for i, h_i in enumerate(hs):
            for j, h_j in enumerate(hs):
                if i == j:
                    continue
                p_i = h_i["params"]
                p_j = h_j["params"]
                # h_i ⊏ h_j: каждая пара (k,v) из p_i есть в p_j,
                # И p_j имеет хотя~бы одну доп.\ пару
                if all(p_j.get(k) == v for k, v in p_i.items()) and \
                   len(p_j) > len(p_i):
                    edges.append({
                        "src": h_i["id"], "tgt": h_j["id"],
                        "type": "subsumption",
                        "layer": layer,
                        "justification":
                            "params(src) ⊏ params(tgt); общая гипотеза"
                            " порождает специализацию"
                    })
    return edges


def build_graph(name: str, hyp_list: list[dict],
                inter_layer: list[tuple]) -> dict:
    sub_edges = subsumption_edges(hyp_list)
    inter_edges = [{"src": s, "tgt": t, "type": "entailment",
                    "justification": j}
                   for s, t, j in inter_layer]
    nodes = {h["id"]: i for i, h in enumerate(hyp_list)}
    return {
        "pipeline": name,
        "n_hypotheses": len(hyp_list),
        "n_subsumption_edges": len(sub_edges),
        "n_inter_layer_edges": len(inter_edges),
        "n_edges_total": len(sub_edges) + len(inter_edges),
        "hypotheses": hyp_list,
        "subsumption_edges": sub_edges,
        "inter_layer_edges": inter_edges,
    }


def summary_per_layer(hyp_list: list[dict]) -> dict:
    counts = {}
    for h in hyp_list:
        counts[h["layer"]] = counts.get(h["layer"], 0) + 1
    return counts


PIPELINE_LAYERS = {
    "rnaseq":      ["QC", "Alignment", "Counting", "DE", "Enrichment"],
    "airrflow":    ["QC", "Assembly", "VDJ", "Clonal", "Repertoire"],
    "sarek":       ["QC", "Alignment", "BQSR", "VariantCall", "Annotation"],
    "atacseq":     ["QC", "Alignment", "Peaks", "DiffAcc", "Motif"],
    "chipseq":     ["QC", "Alignment", "Peaks", "DiffBind", "Motif"],
    "methylseq":   ["QC", "Alignment", "MethCalling", "DMR", "Biology"],
    "hic":         ["QC", "Alignment", "ContactMatrix", "Compartments", "Loops"],
    "ampliseq":    ["QC", "Denoising", "Taxonomy", "Diversity", "DiffAbundance"],
    "mag":         ["QC", "Assembly", "Binning", "Taxonomy", "Function"],
    "viralrecon":  ["QC", "Alignment", "VariantCall", "Consensus", "Phylogenetics"],
    "scrnaseq":    ["QC", "Alignment", "CellMatrix", "Clustering", "Markers"],
    "taxprofiler": ["QC", "HostFilter", "Classification", "Abundance", "Comparative"],
    "eager":       ["QC", "Alignment", "DamageCorrection", "Variant", "Authentication"],
    "cutandrun":   ["QC", "Alignment", "PeakCalling", "DiffBinding", "Motif"],
    "smrnaseq":    ["QC", "Filtering", "miRNAQuant", "DE", "TargetPred"],
    "dualrnaseq":  ["QC", "SplitAlign", "Counting", "DE", "Crosstalk"],
    "bacass":      ["QC", "Assembly", "Polish", "Annotation", "Comparative"],
    "nanoseq":     ["Basecall", "QC", "Alignment", "SVMeth", "Variant"],
    "demultiplex": ["SampleSheet", "Demux", "QC", "Trim", "Output"],
    "hgtseq":      ["QC", "Alignment", "ChimericReads", "HGTEvents", "Annotation"],
}


def main():
    pipelines = [
        ("rnaseq",      "nf-core/rnaseq",      RNASEQ_HYP,      RNASEQ_INTER_LAYER_EDGES),
        ("airrflow",    "nf-core/airrflow",    AIRRFLOW_HYP,    AIRRFLOW_INTER_LAYER_EDGES),
        ("sarek",       "nf-core/sarek",       SAREK_HYP,       SAREK_INTER_LAYER_EDGES),
        ("atacseq",     "nf-core/atacseq",     ATACSEQ_HYP,     ATACSEQ_INTER_LAYER_EDGES),
        ("chipseq",     "nf-core/chipseq",     CHIPSEQ_HYP,     CHIPSEQ_INTER_LAYER_EDGES),
        ("methylseq",   "nf-core/methylseq",   METHYLSEQ_HYP,   METHYLSEQ_INTER_LAYER_EDGES),
        ("hic",         "nf-core/hic",         HIC_HYP,         HIC_INTER_LAYER_EDGES),
        ("ampliseq",    "nf-core/ampliseq",    AMPLISEQ_HYP,    AMPLISEQ_INTER_LAYER_EDGES),
        ("mag",         "nf-core/mag",         MAG_HYP,         MAG_INTER_LAYER_EDGES),
        ("viralrecon",  "nf-core/viralrecon",  VIRALRECON_HYP,  VIRALRECON_INTER_LAYER_EDGES),
        ("scrnaseq",    "nf-core/scrnaseq",    SCRNASEQ_HYP,    SCRNASEQ_INTER_LAYER_EDGES),
        ("taxprofiler", "nf-core/taxprofiler", TAXPROFILER_HYP, TAXPROFILER_INTER_LAYER_EDGES),
        ("eager",       "nf-core/eager",       EAGER_HYP,       EAGER_INTER_LAYER_EDGES),
        ("cutandrun",   "nf-core/cutandrun",   CUTANDRUN_HYP,   CUTANDRUN_INTER_LAYER_EDGES),
        ("smrnaseq",    "nf-core/smrnaseq",    SMRNASEQ_HYP,    SMRNASEQ_INTER_LAYER_EDGES),
        ("dualrnaseq",  "nf-core/dualrnaseq",  DUALRNASEQ_HYP,  DUALRNASEQ_INTER_LAYER_EDGES),
        ("bacass",      "nf-core/bacass",      BACASS_HYP,      BACASS_INTER_LAYER_EDGES),
        ("nanoseq",     "nf-core/nanoseq",     NANOSEQ_HYP,     NANOSEQ_INTER_LAYER_EDGES),
        ("demultiplex", "nf-core/demultiplex", DEMULTIPLEX_HYP, DEMULTIPLEX_INTER_LAYER_EDGES),
        ("hgtseq",      "nf-core/hgtseq",      HGTSEQ_HYP,      HGTSEQ_INTER_LAYER_EDGES),
    ]
    out = {}
    for key, label, hyp_list, inter in pipelines:
        out[key] = build_graph(label, hyp_list, inter)

    OUT.write_text(json.dumps(out, indent=2, ensure_ascii=False),
                   encoding="utf-8")
    print(f"Saved {OUT}\n")

    for key, _, _, _ in pipelines:
        g = out[key]
        print(f"=== {key} ===")
        print(f"  |H| = {g['n_hypotheses']}")
        print(f"  inter-layer edges (entailment): {g['n_inter_layer_edges']}")
        print(f"  intra-layer edges (subsumption): {g['n_subsumption_edges']}")
        print(f"  |E| total = {g['n_edges_total']}")
        print(f"  per-layer counts:")
        for layer in PIPELINE_LAYERS[key]:
            cnt = sum(1 for h in g["hypotheses"] if h["layer"] == layer)
            print(f"    {layer:14s}: {cnt}")
        print()


if __name__ == "__main__":
    main()
